/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was machine generated by Claude.
-/
import Mathlib.Analysis.Fourier.AddCircle
import Mathlib.Analysis.Fourier.FourierTransform
import Mathlib.MeasureTheory.Measure.Haar.InnerProductSpace
import Mathlib.Analysis.Distribution.SchwartzSpace.Basic

/-!
# Carleson's theorem and bounds for anisotropic Carleson operators

This is the statement surface of the formalization. It states two results:

* `anisotropic_carleson`: Theorem 1.1 of J. Roos, *Bounds for anisotropic Carleson operators*,
  J. Fourier Anal. Appl. **25** (2019), no. 5, 2324-2355,
  [doi:10.1007/s00041-018-09657-7](https://doi.org/10.1007/s00041-018-09657-7),
  [arXiv:1710.10962v1](https://arxiv.org/abs/1710.10962v1): a weak type $(2,2)$ a priori bound for
  Carleson operators associated with smooth multipliers that are homogeneous with respect to
  anisotropic dilations of $\mathbb{R}^n$.
* `classical_carleson`: Carleson's theorem, L. Carleson, *On convergence and growth of partial sums
  of Fourier series*, Acta Math. **116** (1966), 135-157,
  [doi:10.1007/BF02392815](https://doi.org/10.1007/BF02392815): the Fourier series of a
  $2\pi$-periodic function that is square integrable on a period converges almost everywhere.

The definitions below are copied verbatim (as declarations) from `CarlesonLT/Defs.lean`.

Conventions and deviations from the paper:

* The Fourier transform is Mathlib's `𝓕`, $\hat f(\xi) = \int f(x) e^{-2\pi i \langle x, \xi \rangle}\,dx$,
  and the Carleson operator uses the kernel $e^{2\pi i \langle x, \xi \rangle}$. The paper does not fix
  a normalization and writes $e^{i x \xi}$; the two versions differ by rescaling the multiplier, which
  preserves the class $\mathcal{M}^{\nu}$ and changes $\|m\|_{\mathcal{M}^{\nu}}$ by a factor depending
  only on $n$, $\alpha$ and $\nu$.
* The bound is stated for Schwartz functions $f$ (an a priori estimate); the paper does not state the
  class of $f$ explicitly.
* The paper's normalization $\alpha_1 = 1$ is not assumed; the dimension is assumed to satisfy
  $n \geq 1$, which is implicit in the paper.
* The partial derivatives $\partial^\beta m(\xi)$ with $|\beta| = k$ are expressed as the $k$-th
  Frechet derivative of $m$ evaluated at standard basis vectors.
-/

namespace CarlesonLT

noncomputable section

open Real Complex Finset ENNReal MeasureTheory Set EuclideanSpace
open scoped InnerProductSpace FourierTransform

/-- The symmetric partial sums
$$ S_N f(x) = \sum_{k=-N}^{N} \hat f(k) e^{ikx} $$
of the Fourier series of a $2\pi$-periodic function $f$, where
$\hat f(k) = \frac{1}{2\pi} \int_0^{2\pi} f(x) e^{-ikx}\,dx$ is Mathlib's `fourierCoeffOn`. -/
def fourierPartialSum (f : ℝ → ℂ) (N : ℕ) (x : ℝ) : ℂ :=
  ∑ n ∈ Finset.Icc (-(N : ℤ)) N,
    fourierCoeffOn two_pi_pos f n * fourier n (x : AddCircle (2 * π))

/-- The Euclidean space $\mathbb{R}^n$. -/
scoped notation "ℝ^" n:max => EuclideanSpace ℝ (Fin n)

variable {n : ℕ}

/-- The Carleson operator associated with a multiplier $m$:
$$ \mathcal{C}_m f(x) = \sup_{N \in \mathbb{R}^n} \left| \int_{\mathbb{R}^n} \hat f(\xi)
  e^{2\pi i \langle x, \xi \rangle} m(\xi - N)\,d\xi \right|, $$
with values in $[0, \infty]$ and Mathlib's Fourier transform $\hat f = $ `𝓕 f`. -/
def carlesonOperator (m : ℝ^n → ℂ) (f : ℝ^n → ℂ) (x : ℝ^n) : ℝ≥0∞ :=
  ⨆ N : ℝ^n, ‖∫ ξ, 𝓕 f ξ * 𝐞 (⟪x, ξ⟫_ℝ) * m (ξ - N)‖ₑ

/-- The weak $L^2$ quasinorm
$\|g\|_{L^{2,\infty}} = \sup_{t} t \, \mu(\{x : g(x) > t\})^{1/2}$ of a function $g$ with values
in $[0, \infty]$, the supremum taken over $t \in [0, \infty]$. -/
def weakL2Norm {X : Type*} [MeasurableSpace X] (μ : Measure X) (g : X → ℝ≥0∞) : ℝ≥0∞ :=
  ⨆ t : ℝ≥0∞, t * μ {x | t < g x} ^ (2⁻¹ : ℝ)

/-- The anisotropic dilations $\delta_t x = (t^{\alpha_1} x_1, \ldots, t^{\alpha_n} x_n)$. -/
def anisoDil (α : Fin n → ℕ) (t : ℝ) (x : ℝ^n) : ℝ^n :=
  WithLp.toLp 2 (fun i ↦ t ^ α i * x i)

/-- The anisotropic norm $\rho(x) = \max_{i} |x_i|^{1/\alpha_i}$. -/
def anisoNorm (α : Fin n → ℕ) (x : ℝ^n) : ℝ := ⨆ i, |x i| ^ ((α i)⁻¹ : ℝ)

/-- The multiplier class $\mathcal{M}^{\nu}$: $m$ is bounded, $\nu$ times continuously
differentiable on $\mathbb{R}^n \setminus \{0\}$, and invariant under the anisotropic dilations,
$m(\delta_t \xi) = m(\xi)$ for all $\xi \neq 0$ and $t > 0$. -/
structure MultiplierClass (α : Fin n → ℕ) (ν : ℕ) (m : ℝ^n → ℂ) : Prop where
  bounded : ∃ C : ℝ, ∀ ξ, ‖m ξ‖ ≤ C
  contDiffOn : ContDiffOn ℝ ν m {0}ᶜ
  homogeneous : ∀ ξ, ξ ≠ 0 → ∀ t : ℝ, 0 < t → m (anisoDil α t ξ) = m ξ

/-- The multiplier norm
$$ \|m\|_{\mathcal{M}^{\nu}} = \sup_{|\beta| \leq \nu} \sup_{\rho(\xi) = 1}
  |\partial^\beta m(\xi)|, $$
where $\partial^\beta m(\xi)$ with $|\beta| = k$ is the $k$-th Frechet derivative of $m$ at $\xi$
evaluated at standard basis vectors $e_{i_1}, \ldots, e_{i_k}$. -/
def multiplierNorm (α : Fin n → ℕ) (ν : ℕ) (m : ℝ^n → ℂ) : ℝ≥0∞ :=
  ⨆ (k ≤ ν) (i : Fin k → Fin n) (ξ : ℝ^n) (_ : anisoNorm α ξ = 1),
    ‖iteratedFDeriv ℝ k m ξ (fun j ↦ single (i j) 1)‖ₑ

end

end CarlesonLT

section

open CarlesonLT
open MeasureTheory Filter Topology Function Real Set SchwartzMap

variable {n : ℕ}

/-- Let $n \geq 1$, let $\alpha \in \mathbb{N}^n$ with $\alpha_i \geq 1$ for all $i$, and let
$\nu_0$ be an integer with $\nu_0 \geq 3 \sum_i \alpha_i + 2$. Then there exists $C > 0$ such that
for every multiplier $m$ in the class $\mathcal{M}^{\nu_0}$ and every Schwartz function $f$ on
$\mathbb{R}^n$,
$$ \|\mathcal{C}_m f\|_{L^{2,\infty}} \leq C \, \|m\|_{\mathcal{M}^{\nu_0}} \, \|f\|_{L^2}. $$ -/
theorem anisotropic_carleson (α : Fin n → ℕ) (hα : ∀ i, 1 ≤ α i) (hn : 0 < n) (ν₀ : ℕ)
    (hν₀ : 3 * (∑ i, α i) + 2 ≤ ν₀) :
      ∃ C : ℝ, 0 < C ∧ ∀ (m : ℝ^n → ℂ), MultiplierClass α ν₀ m → ∀ f : 𝓢(ℝ^n, ℂ),
        weakL2Norm volume (carlesonOperator m f) ≤
          ENNReal.ofReal C * (multiplierNorm α ν₀ m) * eLpNorm f 2 volume := by
  sorry

/-- Let $f : \mathbb{R} \to \mathbb{C}$ be $2\pi$-periodic and square integrable on $[0, 2\pi)$.
Then for almost every $x \in \mathbb{R}$, the partial sums $S_N f(x)$ of the Fourier series of $f$
converge to $f(x)$ as $N \to \infty$. -/
theorem classical_carleson (f : ℝ → ℂ) (hper : Periodic f (2 * π))
    (hf : MemLp f 2 (volume.restrict (Ico 0 (2 * π)))) :
    ∀ᵐ x, Tendsto (fun N ↦ fourierPartialSum f N x) atTop (𝓝 (f x)) := by
  sorry

end
