/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was machine generated by Claude.
-/
import CarlesonLT.Theorems

/-!
# Palomar solution surface

This module is the Palomar solution surface. It imports `CarlesonLT/Theorems.lean`
(module `CarlesonLT.Theorems`), which contains the proved declarations `anisotropic_carleson` and
`classical_carleson` compared against `Challenge.lean`. Their proofs refer to
`Auto.anisotropic_carleson` in `CarlesonLT/Auto/Main.lean` and `Auto.classical_carleson` in
`CarlesonLT/Auto/ClassicalCarleson.lean`, where the actual formalization lives.
-/
