/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/
import CarlesonLT.Auto.Main

/-!
# The classical Carleson theorems

Derived from the anisotropic Carleson theorem `Auto.thm_1_1` (J. Roos, arXiv:1710.10962, Theorem 1.1)
in dimension `n = 1` with the multiplier `m = 1_{(0,∞)}`.

* `Auto.carleson_real_line`: for `f ∈ L²(ℝ)` (as `MemLp f 2`), the partial Fourier integrals
  `S_R f(x) = ∫ f(y) sin(2πR(x−y))/(π(x−y)) dy` converge to `f(x)` for almost every `x`;
  `Auto.carleson_fourierIntegral`: for `f ∈ L¹ ∩ L²`, `∫_{-R}^{R} 𝓕f(ξ) e^{2πixξ} dξ → f(x)` a.e.
* `Auto.carleson_fourierSeries`: **Carleson's theorem** (L. Carleson, *On convergence and growth of
  partial sums of Fourier series*, Acta Math. 116 (1966), 135–157): for a `1`-periodic `f` with
  `MemLp f 2` on `(0,1]`, the symmetric partial sums of its Fourier series converge to `f(x)` for
  almost every `x`. `Auto.classical_carleson` states it for `2π`-periodic `f` with `MemLp f 2` on
  `[0, 2π)`, using Mathlib's Fourier coefficients `fourierCoeffOn` and characters `fourier`.

The proof of the real-line result is the standard one: the maximal partial Fourier integral is
dominated by the Carleson operator, hence of weak type `(2,2)` on Schwartz functions, hence on
`L²` by approximation; a.e. convergence follows from Fourier inversion on a dense class. The
periodic result follows by comparing the Dirichlet kernel with the real-line kernel on a window and
the Riemann–Lebesgue lemma.
-/

open MeasureTheory Real Complex Filter
open scoped InnerProductSpace NNReal ENNReal SchwartzMap ComplexConjugate FourierTransform Topology

noncomputable section

namespace Auto

/-! ### Step 1: the one-dimensional Carleson operator -/

/-- The isometry `ℝ ≃ ℝ¹`, `t ↦ t e₀`. -/
def toR1 : ℝ ≃ₗᵢ[ℝ] Rn 1 :=
  LinearIsometry.toLinearIsometryEquiv
    { toLinearMap := LinearMap.toSpanSingleton ℝ (Rn 1) (EuclideanSpace.single 0 1)
      norm_map' := fun t => by simp [norm_smul] }
    (by simp)

@[simp]
theorem toR1_apply_zero (t : ℝ) : toR1 t 0 = t := by
  simp [toR1]

theorem inner_toR1 (a b : ℝ) : ⟪toR1 a, toR1 b⟫_ℝ = a * b := by
  rw [toR1.inner_map_map, real_inner_eq_re_inner, RCLike.inner_apply, conj_trivial]
  simp [mul_comm]

/-- The exponent vector `α = (1)`. -/
def alpha1 : Fin 1 → ℕ := fun _ => 1

theorem alpha1_pos : ∀ i, 1 ≤ alpha1 i := fun _ => le_rfl

theorem absA_alpha1 : absA alpha1 = 1 := by simp [absA, alpha1]

/-- The multiplier `1_{(0,∞)}` on `ℝ¹`. -/
def mHalf : Rn 1 → ℂ := fun ξ => if 0 < ξ 0 then 1 else 0

theorem classM_mHalf (ν : ℕ) : ClassM alpha1 ν mHalf := by
  refine ⟨⟨1, fun ξ => ?_⟩, ?_, fun ξ hξ t ht => ?_⟩
  · unfold mHalf; split_ifs <;> simp
  · intro ξ hξ
    have hξ0 : ξ 0 ≠ 0 := by
      intro h; apply hξ
      ext i; fin_cases i; simpa using h
    have hc : Continuous fun ζ : Rn 1 => ζ 0 :=
      (continuous_apply 0).comp (PiLp.continuous_ofLp 2 _)
    refine (contDiffAt_const (c := mHalf ξ)).congr_of_eventuallyEq ?_ |>.contDiffWithinAt
    rcases lt_or_gt_of_ne hξ0 with h | h
    · filter_upwards [hc.continuousAt.eventually (gt_mem_nhds h)] with ζ hζ
      simp [mHalf, not_lt.mpr hζ.le, not_lt.mpr h.le]
    · filter_upwards [hc.continuousAt.eventually (lt_mem_nhds h)] with ζ hζ
      simp [mHalf, hζ, h]
  · simp only [mHalf, dil, alpha1, pow_one, PiLp.toLp_apply]
    by_cases h : 0 < ξ 0
    · simp [h, mul_pos ht h]
    · have : ¬ 0 < t * ξ 0 := fun h' => h (pos_of_mul_pos_right h' ht.le)
      simp [h, this]

theorem le_sq_of_mul_rpow_half_le {t : ℝ} (ht : 0 < t) {v : ℝ≥0∞} {K : ℝ} (hK : 0 ≤ K)
    (h : ENNReal.ofReal t * v ^ (1 / 2 : ℝ) ≤ ENNReal.ofReal K) :
    v ≤ ENNReal.ofReal ((K / t) ^ 2) := by
  have h1 : v ^ (1 / 2 : ℝ) ≤ ENNReal.ofReal (K / t) := by
    rw [ENNReal.ofReal_div_of_pos ht, ENNReal.le_div_iff_mul_le (by simp [ht]) (by simp),
      mul_comm]
    exact h
  have h2 : v = (v ^ (1 / 2 : ℝ)) ^ 2 := by
    rw [← ENNReal.rpow_natCast, ← ENNReal.rpow_mul]; norm_num
  rw [h2, ENNReal.ofReal_pow (by positivity)]
  exact pow_le_pow_left₀ bot_le h1 2

/-- **Weak `(2,2)` bound for the one-dimensional Carleson operator** (Theorem 1.1 with `n = 1`,
`m = 1_{(0,∞)}`). -/
theorem carleson_mHalf_weak :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (G : 𝓢(Rn 1, ℂ)) (t : ℝ), 0 < t →
      volume {y | ENNReal.ofReal t < carleson mHalf G y} ≤
        ENNReal.ofReal ((C * (eLpNorm (G : Rn 1 → ℂ) 2 volume).toReal / t) ^ 2) := by
  obtain ⟨C, hC, h⟩ := thm_1_1 alpha1 alpha1_pos one_pos 5 (by rw [absA_alpha1])
  refine ⟨C * (normM alpha1 5 mHalf).toReal, by positivity, fun G t ht => ?_⟩
  have h1 := h mHalf (classM_mHalf 5) G t ht
  rw [mul_assoc] at h1
  exact le_sq_of_mul_rpow_half_le ht (by positivity) (by rw [mul_assoc]; exact h1)


/-! ### Step 2: the Dirichlet kernel of the real line -/

/-- The kernel `D_R(z) = sin(2πRz)/(πz)` (with `D_R(0) = 2R`) of the partial Fourier integrals
`∫_{-R}^{R} f̂(ξ) e^{2πixξ} dξ = ∫ f(y) D_R(x − y) dy`. -/
def dirichletKernel (R z : ℝ) : ℂ :=
  if z = 0 then ((2 * R : ℝ) : ℂ) else ((Real.sin (2 * π * R * z) / (π * z) : ℝ) : ℂ)

theorem dirichletKernel_eq_integral (R z : ℝ) :
    dirichletKernel R z = ∫ ξ in -R..R, Complex.exp (↑(2 * π * (ξ * z)) * Complex.I) := by
  unfold dirichletKernel
  split_ifs with hz
  · subst hz; simp; ring
  · set c : ℂ := ↑(2 * π * z) * Complex.I
    have hc : c ≠ 0 := by
      simp [c, Real.pi_ne_zero, hz]
    have e : ∀ ξ : ℝ, Complex.exp (↑(2 * π * (ξ * z)) * Complex.I) = Complex.exp (c * ξ) := by
      intro ξ; congr 1; simp only [c]; push_cast; ring
    simp_rw [e]
    rw [integral_exp_mul_complex hc]
    simp only [c]
    push_cast
    rw [Complex.sin]
    have hz' : (z : ℂ) ≠ 0 := by exact_mod_cast hz
    have hπ : (π : ℂ) ≠ 0 := by exact_mod_cast Real.pi_ne_zero
    field_simp
    ring_nf
    rw [Complex.I_sq]
    ring_nf

/-- The partial Fourier integral `S_R f(x) = ∫ f(y) D_R(x − y) dy`. -/
def partialFourierIntegral (f : ℝ → ℂ) (R x : ℝ) : ℂ := ∫ y, f y * dirichletKernel R (x - y)

/-- For integrable `f`, `S_R f(x) = ∫_{-R}^{R} 𝓕f(ξ) e^{2πixξ} dξ` (Fubini). -/
theorem integral_fourier_eq_partialFourierIntegral {f : ℝ → ℂ} (hf : Integrable f) {R : ℝ}
    (hR : 0 ≤ R) (x : ℝ) :
    ∫ ξ in -R..R, 𝐞 (ξ * x) • 𝓕 f ξ = partialFourierIntegral f R x := by
  rw [intervalIntegral.integral_of_le (by linarith)]
  unfold partialFourierIntegral
  have h1 : ∀ ξ, 𝐞 (ξ * x) • 𝓕 f ξ = ∫ y, Complex.exp (↑(2 * π * (ξ * (x - y))) * Complex.I) * f y := by
    intro ξ
    rw [Real.fourier_real_eq_integral_exp_smul, Circle.smul_def, smul_eq_mul,
      Real.fourierChar_apply, ← integral_const_mul]
    congr 1; funext y
    rw [smul_eq_mul, ← mul_assoc, ← Complex.exp_add]
    congr 2; push_cast; ring
  simp_rw [h1]
  have hint : Integrable (Function.uncurry fun ξ y =>
      Complex.exp (↑(2 * π * (ξ * (x - y))) * Complex.I) * f y)
      ((volume.restrict (Set.Ioc (-R) R)).prod volume) := by
    have hm : AEStronglyMeasurable (Function.uncurry fun ξ y =>
        Complex.exp (↑(2 * π * (ξ * (x - y))) * Complex.I) * f y)
        ((volume.restrict (Set.Ioc (-R) R)).prod volume) := by
      refine AEStronglyMeasurable.mul ?_ ?_
      · exact (by fun_prop : Continuous fun p : ℝ × ℝ =>
          Complex.exp (↑(2 * π * (p.1 * (x - p.2))) * Complex.I)).aestronglyMeasurable
      · exact hf.aestronglyMeasurable.comp_snd
    refine ((integrable_const (1 : ℝ)).mul_prod hf.norm).mono' hm
      (Filter.Eventually.of_forall fun p => ?_)
    simp only [Function.uncurry, norm_mul, one_mul]
    rw [Complex.norm_exp_ofReal_mul_I, one_mul]
  rw [integral_integral_swap hint]
  congr 1; funext y
  rw [dirichletKernel_eq_integral, intervalIntegral.integral_of_le (by linarith),
    ← integral_const_mul]
  congr 1; funext ξ; ring


/-! ### Step 3: the partial Fourier integrals of Schwartz functions -/

/-- `g ∘ toR1⁻¹` as a Schwartz function on `ℝ¹`. -/
def schwartzToR1 (g : 𝓢(ℝ, ℂ)) : 𝓢(Rn 1, ℂ) :=
  SchwartzMap.compCLMOfContinuousLinearEquiv ℂ toR1.symm.toContinuousLinearEquiv g

@[simp]
theorem coe_schwartzToR1 (g : 𝓢(ℝ, ℂ)) : (schwartzToR1 g : Rn 1 → ℂ) = g ∘ toR1.symm := rfl

theorem integral_toR1 (h : Rn 1 → ℂ) : ∫ w, h w = ∫ ζ : ℝ, h (toR1 ζ) :=
  (toR1.measurePreserving.integral_comp toR1.toHomeomorph.measurableEmbedding h).symm

theorem mHalf_toR1 (u : ℝ) : mHalf (toR1 u) = if 0 < u then 1 else 0 := by
  simp [mHalf]

theorem fhat_schwartzToR1 (g : 𝓢(ℝ, ℂ)) (ζ : ℝ) :
    fhat (schwartzToR1 g) (toR1 ζ) =
      ∫ y : ℝ, Complex.exp (-(Complex.I * ((y * ζ : ℝ) : ℂ))) * g y := by
  unfold fhat
  rw [integral_toR1]
  congr 1; funext y
  rw [coe_schwartzToR1, Function.comp_apply, LinearIsometryEquiv.symm_apply_apply, inner_toR1]

/-- The frequency cut-off integral `J(N) = ∫_{ξ > N} 𝓕g(ξ) e^{2πixξ} dξ`. -/
def cutoffIntegral (g : ℝ → ℂ) (x N : ℝ) : ℂ :=
  ∫ ξ, (Set.Ioi N).indicator (fun ξ => 𝐞 (ξ * x) • 𝓕 g ξ) ξ

theorem integrable_fourier_schwartz (g : 𝓢(ℝ, ℂ)) : Integrable (𝓕 (g : ℝ → ℂ)) := by
  rw [← SchwartzMap.fourier_coe]; exact (𝓕 g).integrable

theorem integrable_char_fourier (g : 𝓢(ℝ, ℂ)) (x : ℝ) :
    Integrable fun ξ => 𝐞 (ξ * x) • 𝓕 (g : ℝ → ℂ) ξ := by
  refine (integrable_fourier_schwartz g).norm.mono' ?_ (Filter.Eventually.of_forall fun ξ => ?_)
  · exact ((Real.continuous_fourierChar.comp (continuous_id.mul continuous_const)).smul
      (SchwartzMap.fourier_coe g ▸ (𝓕 g).continuous)).aestronglyMeasurable
  · rw [Circle.norm_smul]

/-- The Carleson integrand of `mHalf` at the frequency `2πN` is `2π J(N)`. -/
theorem carlesonIntegrand_mHalf (g : 𝓢(ℝ, ℂ)) (x N : ℝ) :
    ∫ w, fhat (schwartzToR1 g) w * Complex.exp (Complex.I * (⟪toR1 x, w⟫_ℝ : ℂ)) *
      mHalf (w - toR1 (2 * π * N)) = (2 * π : ℂ) * cutoffIntegral g x N := by
  rw [integral_toR1]
  set h : ℝ → ℂ := fun ζ => fhat (schwartzToR1 g) (toR1 ζ) *
    Complex.exp (Complex.I * (⟪toR1 x, toR1 ζ⟫_ℝ : ℂ)) * mHalf (toR1 ζ - toR1 (2 * π * N))
  have hsub := Measure.integral_comp_mul_left h (2 * π)
  have hpos : (0 : ℝ) < 2 * π := by positivity
  rw [abs_of_pos (inv_pos.mpr hpos)] at hsub
  have e : ∫ ζ, h ζ = (2 * π : ℂ) * ∫ ξ, h (2 * π * ξ) := by
    rw [hsub, Complex.real_smul, ← mul_assoc]
    push_cast
    rw [mul_inv_cancel₀ (by exact_mod_cast hpos.ne'), one_mul]
  rw [show (∫ ζ, fhat (schwartzToR1 g) (toR1 ζ) *
      Complex.exp (Complex.I * (⟪toR1 x, toR1 ζ⟫_ℝ : ℂ)) * mHalf (toR1 ζ - toR1 (2 * π * N))) =
      ∫ ζ, h ζ from rfl, e]
  congr 1
  unfold cutoffIntegral
  congr 1; funext ξ
  simp only [h]
  rw [← map_sub, mHalf_toR1, fhat_schwartzToR1, inner_toR1, Set.indicator_apply]
  by_cases hξ : N < ξ
  · have h1 : 0 < 2 * π * ξ - 2 * π * N := by nlinarith
    rw [ite_eq_left h1, ite_eq_left (Set.mem_Ioi.mpr hξ), mul_one, Real.fourier_real_eq_integral_exp_smul,
      Circle.smul_def, smul_eq_mul, Real.fourierChar_apply]
    refine (mul_comm _ _).trans ?_
    congr 1
    · congr 1; push_cast; ring
    · congr 1; funext y; rw [smul_eq_mul]; congr 2; push_cast; ring
  · have h1 : ¬ 0 < 2 * π * ξ - 2 * π * N := by
      intro h'; apply hξ; nlinarith
    rw [ite_eq_right h1, ite_eq_right (fun h' => hξ (Set.mem_Ioi.mp h')), mul_zero]

theorem enorm_cutoffIntegral_le (g : 𝓢(ℝ, ℂ)) (x N : ℝ) :
    ‖cutoffIntegral g x N‖ₑ ≤ ENNReal.ofReal (2 * π)⁻¹ * carleson mHalf (schwartzToR1 g) (toR1 x) := by
  have h := carlesonIntegrand_mHalf g x N
  have hle : ‖(2 * π : ℂ) * cutoffIntegral g x N‖ₑ ≤ carleson mHalf (schwartzToR1 g) (toR1 x) := by
    rw [← h]
    exact le_iSup (fun N' => ‖∫ w, fhat (schwartzToR1 g) w *
      Complex.exp (Complex.I * (⟪toR1 x, w⟫_ℝ : ℂ)) * mHalf (w - N')‖ₑ) (toR1 (2 * π * N))
  have hpos : (0 : ℝ) < 2 * π := by positivity
  rw [enorm_mul, show ‖(2 * π : ℂ)‖ₑ = ENNReal.ofReal (2 * π) by
    rw [← ofReal_norm]; congr 1; simp [abs_of_pos Real.pi_pos]] at hle
  calc ‖cutoffIntegral g x N‖ₑ = (ENNReal.ofReal (2 * π))⁻¹ *
        (ENNReal.ofReal (2 * π) * ‖cutoffIntegral g x N‖ₑ) := by
        rw [← mul_assoc, ENNReal.inv_mul_cancel (by simp [Real.pi_pos]) ENNReal.ofReal_ne_top, one_mul]
    _ ≤ _ := by
        rw [ENNReal.ofReal_inv_of_pos hpos]
        exact mul_le_mul' le_rfl hle

/-- `|S_R g(x)| ≤ 𝒞_m G(x)` for Schwartz `g` (`G = g ∘ toR1⁻¹`, `m = 1_{(0,∞)}`). -/
theorem enorm_partialFourierIntegral_le (g : 𝓢(ℝ, ℂ)) {R : ℝ} (hR : 0 ≤ R) (x : ℝ) :
    ‖partialFourierIntegral g R x‖ₑ ≤ carleson mHalf (schwartzToR1 g) (toR1 x) := by
  rw [← integral_fourier_eq_partialFourierIntegral g.integrable hR,
    intervalIntegral.integral_of_le (by linarith), ← integral_indicator measurableSet_Ioc]
  have hi := integrable_char_fourier g x
  have e : (Set.Ioc (-R) R).indicator (fun ξ => 𝐞 (ξ * x) • 𝓕 (g : ℝ → ℂ) ξ) =
      fun ξ => (Set.Ioi (-R)).indicator (fun ξ => 𝐞 (ξ * x) • 𝓕 (g : ℝ → ℂ) ξ) ξ -
        (Set.Ioi R).indicator (fun ξ => 𝐞 (ξ * x) • 𝓕 (g : ℝ → ℂ) ξ) ξ := by
    funext ξ
    simp only [Set.indicator_apply, Set.mem_Ioc, Set.mem_Ioi]
    by_cases h1 : -R < ξ <;> by_cases h2 : R < ξ <;> simp [h1, h2]; linarith
  rw [e, integral_sub (hi.indicator measurableSet_Ioi) (hi.indicator measurableSet_Ioi)]
  refine (enorm_sub_le).trans ?_
  have h1 := enorm_cutoffIntegral_le g x (-R)
  have h2 := enorm_cutoffIntegral_le g x R
  unfold cutoffIntegral at h1 h2
  refine (add_le_add h1 h2).trans ?_
  rw [← add_mul, ← two_mul]
  have h21 : 2 * ENNReal.ofReal (2 * π)⁻¹ ≤ 1 := by
    rw [← ENNReal.ofReal_ofNat, ← ENNReal.ofReal_mul (by norm_num), ENNReal.ofReal_le_one,
      inv_eq_one_div, mul_one_div, div_le_one (by positivity)]
    nlinarith [Real.pi_gt_three]
  calc 2 * ENNReal.ofReal (2 * π)⁻¹ * carleson mHalf (schwartzToR1 g) (toR1 x)
      ≤ 1 * carleson mHalf (schwartzToR1 g) (toR1 x) := mul_le_mul' h21 le_rfl
    _ = _ := one_mul _


/-- The maximal partial Fourier integral of a Schwartz function satisfies the weak `(2,2)` bound. -/
theorem partialFourier_weak_schwartz :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (g : 𝓢(ℝ, ℂ)) (t : ℝ), 0 < t →
      volume {x | ∃ R, 0 ≤ R ∧ ENNReal.ofReal t < ‖partialFourierIntegral g R x‖ₑ} ≤
        ENNReal.ofReal ((C * (eLpNorm (g : ℝ → ℂ) 2 volume).toReal / t) ^ 2) := by
  obtain ⟨C, hC, h⟩ := carleson_mHalf_weak
  refine ⟨C, hC, fun g t ht => ?_⟩
  have hsub : {x | ∃ R, 0 ≤ R ∧ ENNReal.ofReal t < ‖partialFourierIntegral g R x‖ₑ} ⊆
      toR1 ⁻¹' {y | ENNReal.ofReal t < carleson mHalf (schwartzToR1 g) y} := by
    rintro x ⟨R, hR, hx⟩
    exact lt_of_lt_of_le hx (enorm_partialFourierIntegral_le g hR x)
  have hmp : MeasurePreserving (toR1.toHomeomorph.toMeasurableEquiv) volume volume :=
    toR1.measurePreserving
  have hvol := hmp.measure_preimage_equiv {y | ENNReal.ofReal t < carleson mHalf (schwartzToR1 g) y}
  have hnorm : eLpNorm (schwartzToR1 g : Rn 1 → ℂ) 2 volume = eLpNorm (g : ℝ → ℂ) 2 volume := by
    rw [coe_schwartzToR1]
    exact eLpNorm_comp_measurePreserving g.continuous.aestronglyMeasurable
      toR1.symm.measurePreserving
  refine (measure_mono hsub).trans (le_of_eq_of_le hvol ?_)
  have := h (schwartzToR1 g) t ht
  rwa [hnorm] at this

/-! ### Step 4: the partial Fourier integrals of `L²` functions -/

theorem norm_dirichletKernel_le {R : ℝ} (hR : 0 ≤ R) (z : ℝ) :
    ‖dirichletKernel R z‖ ≤ (4 * R + 2) * (1 + |z|)⁻¹ := by
  have hz1 : 0 < 1 + |z| := by positivity
  rw [← div_eq_mul_inv, le_div_iff₀ hz1]
  unfold dirichletKernel
  split_ifs with hz
  · subst hz; simp [abs_of_nonneg hR]; linarith
  · rw [Complex.norm_real, Real.norm_eq_abs, abs_div, abs_mul, abs_of_pos Real.pi_pos]
    have hzp : 0 < |z| := abs_pos.mpr hz
    rw [div_mul_eq_mul_div, div_le_iff₀ (by positivity)]
    rcases le_or_gt |z| 1 with h1 | h1
    · have hs : |Real.sin (2 * π * R * z)| ≤ 2 * π * R * |z| := by
        have := Real.abs_sin_le_abs (x := 2 * π * R * z)
        rwa [abs_mul, abs_of_nonneg (by positivity : (0 : ℝ) ≤ 2 * π * R)] at this
      calc |Real.sin (2 * π * R * z)| * (1 + |z|) ≤ (2 * π * R * |z|) * 2 :=
            mul_le_mul hs (by linarith) (by positivity) (by positivity)
        _ ≤ (4 * R + 2) * (π * |z|) := by nlinarith [Real.pi_pos, abs_nonneg z]
    · have hs := Real.abs_sin_le_one (2 * π * R * z)
      calc |Real.sin (2 * π * R * z)| * (1 + |z|) ≤ 1 * (1 + |z|) :=
            mul_le_mul_of_nonneg_right hs (by positivity)
        _ ≤ 2 * (π * |z|) := by nlinarith [Real.pi_gt_three]
        _ ≤ (4 * R + 2) * (π * |z|) := by
            have : 0 ≤ π * |z| := by positivity
            nlinarith

theorem measurable_dirichletKernel (R : ℝ) : Measurable (dirichletKernel R) := by
  unfold dirichletKernel
  refine Measurable.ite (measurableSet_singleton 0) measurable_const ?_
  exact Complex.measurable_ofReal.comp (by fun_prop)

theorem memLp_dirichletKernel {R : ℝ} (hR : 0 ≤ R) (x : ℝ) :
    MemLp (fun y => dirichletKernel R (x - y)) 2 volume := by
  have hw : MemLp (fun y : ℝ => (1 + |x - y|)⁻¹) 2 volume := by
    have hm : AEStronglyMeasurable (fun y : ℝ => (1 + |x - y|)⁻¹) volume :=
      (by fun_prop : Measurable fun y : ℝ => (1 + |x - y|)⁻¹).aestronglyMeasurable
    rw [memLp_two_iff_integrable_sq hm]
    have h := (integrable_one_add_norm (E := ℝ) (μ := volume) (r := 2) (by norm_num)).comp_sub_left x
    refine h.congr (Filter.Eventually.of_forall fun y => ?_)
    simp only [Real.norm_eq_abs]
    rw [Real.rpow_neg (by positivity), inv_pow, Real.rpow_two]
  refine (hw.const_mul (4 * R + 2)).of_le
    ((measurable_dirichletKernel R).comp (measurable_const.sub measurable_id)).aestronglyMeasurable
    (Filter.Eventually.of_forall fun y => ?_)
  rw [Real.norm_eq_abs, abs_mul, abs_of_nonneg (by positivity : (0 : ℝ) ≤ 4 * R + 2),
    abs_of_pos (by positivity : (0 : ℝ) < (1 + |x - y|)⁻¹)]
  exact norm_dirichletKernel_le hR _

theorem integrable_mul_dirichletKernel {f : ℝ → ℂ} (hf : MemLp f 2 volume) {R : ℝ} (hR : 0 ≤ R)
    (x : ℝ) : Integrable fun y => f y * dirichletKernel R (x - y) :=
  hf.integrable_mul (memLp_dirichletKernel hR x)

theorem partialFourierIntegral_sub {f g : ℝ → ℂ} (hf : MemLp f 2 volume) (hg : MemLp g 2 volume)
    {R : ℝ} (hR : 0 ≤ R) (x : ℝ) :
    partialFourierIntegral (f - g) R x = partialFourierIntegral f R x - partialFourierIntegral g R x := by
  unfold partialFourierIntegral
  rw [← integral_sub (integrable_mul_dirichletKernel hf hR x) (integrable_mul_dirichletKernel hg hR x)]
  congr 1; funext y; simp only [Pi.sub_apply]; ring

/-- Cauchy–Schwarz for the pairing. -/
theorem enorm_integral_mul_le {u v : ℝ → ℂ} (hu : MemLp u 2 volume) (hv : MemLp v 2 volume) :
    ‖∫ y, u y * v y‖ₑ ≤ eLpNorm u 2 volume * eLpNorm v 2 volume := by
  refine (enorm_integral_le_lintegral_enorm _).trans ?_
  simp_rw [enorm_mul]
  have h := ENNReal.lintegral_mul_le_Lp_mul_Lq volume Real.HolderConjugate.two_two
    hu.aestronglyMeasurable.enorm hv.aestronglyMeasurable.enorm
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal (by norm_num) (by norm_num) hu.aestronglyMeasurable,
    eLpNorm_eq_lintegral_rpow_enorm_toReal (by norm_num) (by norm_num) hv.aestronglyMeasurable]
  simpa using h

/-- `S_R f(x)` depends continuously on `f ∈ L²`. -/
theorem enorm_partialFourierIntegral_sub_le {f g : ℝ → ℂ} (hf : MemLp f 2 volume)
    (hg : MemLp g 2 volume) {R : ℝ} (hR : 0 ≤ R) (x : ℝ) :
    ‖partialFourierIntegral f R x - partialFourierIntegral g R x‖ₑ ≤
      eLpNorm (f - g) 2 volume * eLpNorm (fun y => dirichletKernel R (x - y)) 2 volume := by
  rw [← partialFourierIntegral_sub hf hg hR]
  exact enorm_integral_mul_le (hf.sub hg) (memLp_dirichletKernel hR x)


/-- Smooth compactly supported approximation of `L²` functions, as Schwartz functions. -/
theorem exists_schwartz_eLpNorm_sub_le {f : ℝ → ℂ} (hf : MemLp f 2 volume) {ε : ℝ} (hε : 0 < ε) :
    ∃ g : 𝓢(ℝ, ℂ), eLpNorm (f - (g : ℝ → ℂ)) 2 volume ≤ ENNReal.ofReal ε := by
  obtain ⟨g, hg1, hg2, hg3⟩ := hf.exist_eLpNorm_sub_le (by norm_num) (by norm_num) hε
  exact ⟨hg1.toSchwartzMap hg2, hg3⟩

theorem toReal_eLpNorm_le_add {f g : ℝ → ℂ} (hf : MemLp f 2 volume) (hg : MemLp g 2 volume) :
    (eLpNorm g 2 volume).toReal ≤ (eLpNorm f 2 volume).toReal + (eLpNorm (f - g) 2 volume).toReal := by
  have h : eLpNorm g 2 volume ≤ eLpNorm f 2 volume + eLpNorm (f - g) 2 volume := by
    have e : g = f - (f - g) := by abel
    calc eLpNorm g 2 volume = eLpNorm (f - (f - g)) 2 volume := by rw [← e]
      _ ≤ _ := eLpNorm_sub_le (by norm_num)
  rw [← ENNReal.toReal_add hf.eLpNorm_ne_top (hf.sub hg).eLpNorm_ne_top]
  exact ENNReal.toReal_mono (ENNReal.add_ne_top.mpr ⟨hf.eLpNorm_ne_top, (hf.sub hg).eLpNorm_ne_top⟩) h

/-- **The maximal partial Fourier integral is of weak type `(2,2)` on `L²(ℝ)`.** -/
theorem partialFourier_weak :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (f : ℝ → ℂ), MemLp f 2 volume → ∀ (t : ℝ), 0 < t →
      volume {x | ∃ R, 0 ≤ R ∧ ENNReal.ofReal t < ‖partialFourierIntegral f R x‖ₑ} ≤
        ENNReal.ofReal ((C * (eLpNorm f 2 volume).toReal / t) ^ 2) := by
  obtain ⟨C, hC, hS⟩ := partialFourier_weak_schwartz
  refine ⟨C, hC, fun f hf t ht => ?_⟩
  have happ : ∀ j : ℕ, ∃ g : 𝓢(ℝ, ℂ), eLpNorm (f - (g : ℝ → ℂ)) 2 volume ≤
      ENNReal.ofReal (1 / ((j : ℝ) + 1)) := fun j => exists_schwartz_eLpNorm_sub_le hf (by positivity)
  choose g hg using happ
  set B : ℕ → Set ℝ := fun j =>
    {x | ∃ R, 0 ≤ R ∧ ENNReal.ofReal t < ‖partialFourierIntegral (g j) R x‖ₑ}
  set bnd : ℕ → ℝ≥0∞ := fun j => ENNReal.ofReal ((C * ((eLpNorm f 2 volume).toReal +
    1 / ((j : ℝ) + 1)) / t) ^ 2)
  have hB : ∀ j, volume (B j) ≤ bnd j := by
    intro j
    refine (hS (g j) t ht).trans (ENNReal.ofReal_le_ofReal ?_)
    refine pow_le_pow_left₀ (by positivity) (div_le_div_of_nonneg_right ?_ ht.le) 2
    refine mul_le_mul_of_nonneg_left ?_ hC
    refine (toReal_eLpNorm_le_add hf ((g j).memLp 2)).trans (add_le_add le_rfl ?_)
    exact ENNReal.toReal_le_of_le_ofReal (by positivity) (hg j)
  have hbnd : Tendsto bnd atTop (𝓝 (ENNReal.ofReal ((C * (eLpNorm f 2 volume).toReal / t) ^ 2))) := by
    refine ENNReal.tendsto_ofReal ?_
    have h1 : Tendsto (fun j : ℕ => 1 / ((j : ℝ) + 1)) atTop (𝓝 0) := tendsto_one_div_add_atTop_nhds_zero_nat
    have h2 := ((((h1.const_add ((eLpNorm f 2 volume).toReal)).const_mul C).div_const t).pow 2)
    simpa using h2
  -- the level set is in the lower limit of the `B j`
  have hsub : {x | ∃ R, 0 ≤ R ∧ ENNReal.ofReal t < ‖partialFourierIntegral f R x‖ₑ} ⊆
      ⋃ k, ⋂ j ∈ Set.Ici k, B j := by
    rintro x ⟨R, hR, hx⟩
    set K := eLpNorm (fun y => dirichletKernel R (x - y)) 2 volume
    have hK : K ≠ ⊤ := (memLp_dirichletKernel hR x).eLpNorm_ne_top
    have hconv : Tendsto (fun j => partialFourierIntegral (g j) R x) atTop
        (𝓝 (partialFourierIntegral f R x)) := by
      rw [tendsto_iff_norm_sub_tendsto_zero]
      refine squeeze_zero (fun j => norm_nonneg _) (fun j => ?_)
        ((tendsto_one_div_add_atTop_nhds_zero_nat.mul_const K.toReal).trans (by simp))
      have h1 := enorm_partialFourierIntegral_sub_le ((g j).memLp 2) hf hR x
      rw [← eLpNorm_neg, neg_sub] at h1
      have h2 : ‖partialFourierIntegral (g j) R x - partialFourierIntegral f R x‖ₑ ≤
          ENNReal.ofReal (1 / ((j : ℝ) + 1)) * K := h1.trans (mul_le_mul' (hg j) le_rfl)
      rw [← ofReal_norm, ← ENNReal.ofReal_toReal hK, ← ENNReal.ofReal_mul (by positivity),
        ENNReal.ofReal_le_ofReal_iff (by positivity)] at h2
      exact h2
    have hev := ((continuous_enorm.tendsto _).comp hconv).eventually (lt_mem_nhds hx)
    obtain ⟨k, hk⟩ := Filter.eventually_atTop.mp hev
    exact Set.mem_iUnion.mpr ⟨k, Set.mem_iInter₂.mpr fun j hj => ⟨R, hR, hk j hj⟩⟩
  have hmono : Monotone fun k => ⋂ j ∈ Set.Ici k, B j := fun k l hkl =>
    Set.biInter_subset_biInter_left fun j (hj : l ≤ j) => (show k ≤ j from hkl.trans hj)
  refine (measure_mono hsub).trans ?_
  rw [hmono.measure_iUnion]
  refine iSup_le fun k => ?_
  refine ge_of_tendsto hbnd (Filter.eventually_atTop.mpr ⟨k, fun j hj => ?_⟩)
  exact (measure_mono (Set.biInter_subset_of_mem (show j ∈ Set.Ici k from hj))).trans (hB j)

/-! ### Step 5: almost everywhere convergence on the real line -/

theorem tendsto_partialFourierIntegral_schwartz (g : 𝓢(ℝ, ℂ)) (x : ℝ) :
    Tendsto (fun R => partialFourierIntegral g R x) atTop (𝓝 (g x)) := by
  have hi := integrable_char_fourier g x
  have h1 := intervalIntegral_tendsto_integral hi tendsto_neg_atTop_atBot tendsto_id
  have hinv : ∫ ξ, 𝐞 (ξ * x) • 𝓕 (g : ℝ → ℂ) ξ = g x := by
    have := congrFun (Continuous.fourierInv_fourier_eq g.continuous g.integrable
      (integrable_fourier_schwartz g)) x
    rw [fourierInv_eq] at this
    rw [← this]
    congr 1; funext ξ
    congr 2
    simp [mul_comm]
  rw [hinv] at h1
  refine h1.congr' ?_
  filter_upwards [Filter.eventually_ge_atTop 0] with R hR
  exact integral_fourier_eq_partialFourierIntegral g.integrable hR x


/-- The exceptional set for the precision `ε`. -/
theorem volume_bad_eq_zero {f : ℝ → ℂ} (hf : MemLp f 2 volume) {ε : ℝ} (hε : 0 < ε) :
    volume {x | ¬ ∀ᶠ R in atTop, ‖partialFourierIntegral f R x - f x‖ < ε} = 0 := by
  obtain ⟨C, hC, hW⟩ := partialFourier_weak
  set Bad := {x | ¬ ∀ᶠ R in atTop, ‖partialFourierIntegral f R x - f x‖ < ε}
  set K : ℝ := (3 * C / ε) ^ 2 + (3 / ε) ^ 2
  have hδ : ∀ δ : ℝ, 0 < δ → volume Bad ≤ ENNReal.ofReal (K * δ ^ 2) := by
    intro δ hδ
    obtain ⟨g, hg⟩ := exists_schwartz_eLpNorm_sub_le hf hδ
    set h := f - (g : ℝ → ℂ)
    have hh : MemLp h 2 volume := hf.sub (g.memLp 2)
    have hsub : Bad ⊆ {x | ∃ R, 0 ≤ R ∧ ENNReal.ofReal (ε / 3) < ‖partialFourierIntegral h R x‖ₑ} ∪
        {x | ENNReal.ofReal (ε / 3) ≤ ‖h x‖ₑ} := by
      intro x hx
      by_contra hcon
      simp only [Set.mem_union, Set.mem_ofPred_eq, not_or, not_exists, not_and, not_lt] at hcon
      obtain ⟨h1, h2⟩ := hcon
      apply hx
      have hg' := (tendsto_partialFourierIntegral_schwartz g x)
      rw [tendsto_iff_norm_sub_tendsto_zero] at hg'
      filter_upwards [hg'.eventually (gt_mem_nhds (by positivity : (0 : ℝ) < ε / 3)),
        Filter.eventually_ge_atTop 0] with R hR hR0
      have e : partialFourierIntegral f R x - f x = partialFourierIntegral h R x +
          (partialFourierIntegral g R x - g x) - h x := by
        rw [partialFourierIntegral_sub hf (g.memLp 2) hR0]
        simp only [h, Pi.sub_apply]; ring
      have n1 : ‖partialFourierIntegral h R x‖ ≤ ε / 3 := by
        have := h1 R hR0
        rwa [← ofReal_norm, ENNReal.ofReal_le_ofReal_iff (by positivity)] at this
      have n2 : ‖h x‖ < ε / 3 := by
        have := h2
        rw [← ofReal_norm] at this
        exact (ENNReal.ofReal_lt_ofReal_iff (by positivity)).mp (not_le.mp this)
      rw [e]
      calc ‖partialFourierIntegral h R x + (partialFourierIntegral g R x - g x) - h x‖
          ≤ ‖partialFourierIntegral h R x‖ + ‖partialFourierIntegral g R x - g x‖ + ‖h x‖ :=
            (norm_sub_le _ _).trans (add_le_add (norm_add_le _ _) le_rfl)
        _ < ε := by linarith
    have hnorm : (eLpNorm h 2 volume).toReal ≤ δ := ENNReal.toReal_le_of_le_ofReal hδ.le hg
    have b1 := hW h hh (ε / 3) (by positivity)
    have b2 := meas_ge_le_mul_pow_eLpNorm_enorm volume (p := 2) (by norm_num) (by norm_num)
      (f := h) (ε := ENNReal.ofReal (ε / 3)) (by simp [hε]) (by simp)
    refine (measure_mono hsub).trans ((measure_union_le _ _).trans ?_)
    have b2' : volume {x | ENNReal.ofReal (ε / 3) ≤ ‖h x‖ₑ} ≤ ENNReal.ofReal ((3 / ε) ^ 2 * δ ^ 2) := by
      refine b2.trans ?_
      rw [ENNReal.toReal_ofNat, ENNReal.rpow_two, ENNReal.rpow_two,
        ← ENNReal.ofReal_inv_of_pos (by positivity), ← ENNReal.ofReal_pow (by positivity),
        ← ENNReal.ofReal_toReal hh.eLpNorm_ne_top, ← ENNReal.ofReal_pow ENNReal.toReal_nonneg,
        ← ENNReal.ofReal_mul (by positivity)]
      refine ENNReal.ofReal_le_ofReal ?_
      rw [show (ε / 3)⁻¹ = 3 / ε by field_simp]
      gcongr
    have b1' : volume {x | ∃ R, 0 ≤ R ∧ ENNReal.ofReal (ε / 3) < ‖partialFourierIntegral h R x‖ₑ} ≤
        ENNReal.ofReal ((3 * C / ε) ^ 2 * δ ^ 2) := by
      refine b1.trans (ENNReal.ofReal_le_ofReal ?_)
      rw [← mul_pow]
      refine pow_le_pow_left₀ (by positivity) ?_ 2
      rw [div_div_eq_mul_div, div_mul_eq_mul_div]
      refine div_le_div_of_nonneg_right ?_ hε.le
      nlinarith [ENNReal.toReal_nonneg (a := eLpNorm h 2 volume)]
    refine (add_le_add b1' b2').trans (le_of_eq ?_)
    rw [← ENNReal.ofReal_add (by positivity) (by positivity)]
    congr 1; ring
  have hlim : Tendsto (fun j : ℕ => ENNReal.ofReal (K * (1 / ((j : ℝ) + 1)) ^ 2)) atTop (𝓝 0) := by
    rw [← ENNReal.ofReal_zero]
    refine ENNReal.tendsto_ofReal ?_
    have := (tendsto_one_div_add_atTop_nhds_zero_nat.pow 2).const_mul K
    simpa using this
  exact le_antisymm (ge_of_tendsto hlim (Filter.Eventually.of_forall fun j => hδ _ (by positivity)))
    bot_le

/-- **Carleson's theorem on the real line (kernel form)**: for `f ∈ L²(ℝ)`, the partial Fourier
integrals `S_R f(x) = ∫ f(y) sin(2πR(x−y))/(π(x−y)) dy` converge to `f(x)` for almost every `x`. -/
theorem carleson_real_line {f : ℝ → ℂ} (hf : MemLp f 2 volume) :
    ∀ᵐ x, Tendsto (fun R => partialFourierIntegral f R x) atTop (𝓝 (f x)) := by
  have h : ∀ k : ℕ, ∀ᵐ x, ∀ᶠ R in atTop,
      ‖partialFourierIntegral f R x - f x‖ < 1 / ((k : ℝ) + 1) := by
    intro k
    rw [ae_iff]
    exact volume_bad_eq_zero hf (by positivity)
  rw [← ae_all_iff] at h
  filter_upwards [h] with x hx
  rw [tendsto_iff_norm_sub_tendsto_zero]
  refine Metric.tendsto_nhds.mpr fun ε hε => ?_
  obtain ⟨k, hk⟩ := exists_nat_one_div_lt hε
  filter_upwards [hx k] with R hR
  rw [dist_zero_right, norm_norm]
  exact hR.trans hk

/-- **Carleson's theorem on the real line (Fourier integral form)**: for integrable `f ∈ L²(ℝ)`,
`∫_{-R}^{R} 𝓕f(ξ) e^{2πixξ} dξ → f(x)` as `R → ∞` for almost every `x`. -/
theorem carleson_fourierIntegral {f : ℝ → ℂ} (hf1 : Integrable f) (hf : MemLp f 2 volume) :
    ∀ᵐ x, Tendsto (fun R => ∫ ξ in -R..R, 𝐞 (ξ * x) • 𝓕 f ξ) atTop (𝓝 (f x)) := by
  filter_upwards [carleson_real_line hf] with x hx
  refine hx.congr' ?_
  filter_upwards [Filter.eventually_ge_atTop 0] with R hR
  exact (integral_fourier_eq_partialFourierIntegral hf1 hR x).symm

/-! ### Step 6: the Dirichlet kernel of the circle -/

/-- The Fourier coefficients `f̂(k) = ∫_0^1 f(y) e^{-2πiky} dy` of a `1`-periodic function. -/
def fourierCoeff1 (f : ℝ → ℂ) (k : ℤ) : ℂ :=
  ∫ y in (0 : ℝ)..1, Complex.exp (-(2 * π * Complex.I * k * y)) * f y

/-- The symmetric partial sums `S_N f(x) = ∑_{|k| ≤ N} f̂(k) e^{2πikx}` of the Fourier series. -/
def fourierPartialSum1 (f : ℝ → ℂ) (N : ℕ) (x : ℝ) : ℂ :=
  ∑ k ∈ Finset.Icc (-(N : ℤ)) N, fourierCoeff1 f k * Complex.exp (2 * π * Complex.I * k * x)

/-- The Dirichlet kernel `D_N(z) = ∑_{|k| ≤ N} e^{2πikz}`. -/
def dirichletPer (N : ℕ) (z : ℝ) : ℂ :=
  ∑ k ∈ Finset.Icc (-(N : ℤ)) N, Complex.exp (2 * π * Complex.I * k * z)

theorem Icc_succ_eq (N : ℕ) : Finset.Icc (-((N + 1 : ℕ) : ℤ)) ((N + 1 : ℕ) : ℤ) =
    insert (-((N + 1 : ℕ) : ℤ)) (insert ((N + 1 : ℕ) : ℤ) (Finset.Icc (-(N : ℤ)) N)) := by
  ext k; simp only [Finset.mem_Icc, Finset.mem_insert]; push_cast; omega

theorem zpow_sum_mul (w : ℂ) (hw : w ≠ 0) (N : ℕ) :
    (∑ k ∈ Finset.Icc (-(N : ℤ)) N, w ^ (2 * k)) * (w - w⁻¹) =
      w ^ (2 * (N : ℤ) + 1) - w ^ (-(2 * (N : ℤ) + 1)) := by
  induction N with
  | zero => simp [zpow_neg]
  | succ N ih =>
    rw [Icc_succ_eq, Finset.sum_insert (by simp; omega), Finset.sum_insert (by simp),
      add_mul, add_mul, ih]
    push_cast
    have e1 : w ^ (2 * -((N : ℤ) + 1)) = w ^ (-(2 * (N : ℤ) + 1)) * w⁻¹ := by
      rw [← zpow_neg_one, ← zpow_add₀ hw]; ring_nf
    have e2 : w ^ (2 * ((N : ℤ) + 1)) = w ^ (2 * (N : ℤ) + 1) * w := by
      rw [← zpow_add_one₀ hw]; ring_nf
    have e3 : w ^ (2 * ((N : ℤ) + 1) + 1) = w ^ (2 * (N : ℤ) + 1) * w * w := by
      rw [zpow_add_one₀ hw, e2]
    have e4 : w ^ (-(2 * ((N : ℤ) + 1) + 1)) = w ^ (-(2 * (N : ℤ) + 1)) * w⁻¹ * w⁻¹ := by
      rw [← zpow_neg_one, ← zpow_add₀ hw, ← zpow_add₀ hw]; ring_nf
    rw [e1, e2, e3, e4]
    field_simp
    ring

/-- `D_N(z) sin(πz) = sin((2N+1)πz)`. -/
theorem dirichletPer_mul_sin (N : ℕ) (z : ℝ) :
    dirichletPer N z * (Real.sin (π * z) : ℂ) = (Real.sin ((2 * N + 1) * π * z) : ℂ) := by
  set w := Complex.exp (π * Complex.I * z)
  have hw : w ≠ 0 := Complex.exp_ne_zero _
  have hk : ∀ k : ℤ, Complex.exp (2 * π * Complex.I * k * z) = w ^ (2 * k) := by
    intro k
    rw [← Complex.exp_int_mul]; congr 1; push_cast; ring
  have hw1 : Complex.exp (↑(π * z) * Complex.I) = w := by simp only [w]; congr 1; push_cast; ring
  have hw2 : Complex.exp (-↑(π * z) * Complex.I) = w⁻¹ := by
    simp only [w]; rw [← Complex.exp_neg]; congr 1; push_cast; ring
  have hw3 : Complex.exp (↑((2 * N + 1) * π * z) * Complex.I) = w ^ (2 * (N : ℤ) + 1) := by
    simp only [w]; rw [← Complex.exp_int_mul]; congr 1; push_cast; ring
  have hw4 : Complex.exp (-↑((2 * N + 1) * π * z) * Complex.I) = w ^ (-(2 * (N : ℤ) + 1)) := by
    simp only [w]; rw [← Complex.exp_int_mul]; congr 1; push_cast; ring
  unfold dirichletPer
  simp_rw [hk]
  rw [Complex.ofReal_sin, Complex.ofReal_sin, Complex.sin, Complex.sin, hw1, hw2, hw3, hw4]
  linear_combination (-(Complex.I / 2)) * zpow_sum_mul w hw N


/-- The correction `φ(z) = 1/sin(πz) − 1/(πz)` (with `φ(0) = 0`). -/
def corrPhi (z : ℝ) : ℝ := if z = 0 then 0 else 1 / Real.sin (π * z) - 1 / (π * z)

theorem corr_bound_pos {u : ℝ} (hu : 0 < u) (hu' : u ≤ π / 2) :
    0 ≤ 1 / Real.sin u - 1 / u ∧ 1 / Real.sin u - 1 / u ≤ 1 := by
  have hs : 0 < Real.sin u := Real.sin_pos_of_pos_of_lt_pi hu (by linarith [Real.pi_pos])
  have hsu : Real.sin u ≤ u := Real.sin_le hu.le
  have hj : 2 / π * u ≤ Real.sin u := Real.mul_le_sin hu.le hu'
  have hc : u - u ^ 3 / 6 < Real.sin u := Real.sin_gt_sub_cube hu
  have hπ := Real.pi_gt_three
  have hπ' := Real.pi_lt_four
  rw [div_sub_div _ _ hs.ne' hu.ne']
  constructor
  · apply div_nonneg <;> nlinarith
  · rw [div_le_one (by positivity)]
    have h1 : u * (2 / π * u) ≤ u * Real.sin u := mul_le_mul_of_nonneg_left hj hu.le
    have h2 : u ^ 3 / 6 ≤ u * (2 / π * u) := by
      rw [show u * (2 / π * u) = u ^ 2 * (2 / π) by ring]
      have : u ≤ 12 / π := by
        rw [le_div_iff₀ (by positivity)]; nlinarith
      have h3 : u / 6 ≤ 2 / π := by
        rw [div_le_div_iff₀ (by norm_num) (by positivity)]
        rw [le_div_iff₀ (by positivity)] at this; linarith
      nlinarith [sq_nonneg u]
    nlinarith

theorem abs_corrPhi_le {z : ℝ} (hz : |z| ≤ 1 / 2) : |corrPhi z| ≤ 1 := by
  unfold corrPhi
  split_ifs with h0
  · simp
  · rcases lt_or_gt_of_ne h0 with hneg | hpos
    · have h := corr_bound_pos (u := π * -z) (by nlinarith [Real.pi_pos])
        (by rw [abs_of_neg hneg] at hz; nlinarith [Real.pi_pos])
      have e : 1 / Real.sin (π * z) - 1 / (π * z) = -(1 / Real.sin (π * -z) - 1 / (π * -z)) := by
        rw [mul_neg, Real.sin_neg]; ring
      rw [e, abs_neg, abs_of_nonneg h.1]; exact h.2
    · have h := corr_bound_pos (u := π * z) (by positivity)
        (by rw [abs_of_pos hpos] at hz; nlinarith [Real.pi_pos])
      rw [abs_of_nonneg h.1]; exact h.2

/-- `ψ = φ` on `[−1/2, 1/2)` and `−1/(πz)` outside. -/
def corrPsi (z : ℝ) : ℝ := if z ∈ Set.Ico (-1 / 2 : ℝ) (1 / 2) then corrPhi z else -(1 / (π * z))

theorem abs_corrPsi_le (z : ℝ) : |corrPsi z| ≤ 1 := by
  unfold corrPsi
  split_ifs with h
  · exact abs_corrPhi_le (abs_le.mpr ⟨by linarith [h.1], h.2.le⟩)
  · have hz : 1 / 2 ≤ |z| := by
      simp only [Set.mem_Ico, not_and_or, not_le, not_lt] at h
      rcases h with h | h
      · rw [abs_of_neg (by linarith)]; linarith
      · rw [abs_of_pos (by linarith)]; linarith
    rw [abs_neg, abs_div, abs_one, abs_mul, abs_of_pos Real.pi_pos, div_le_one (by positivity)]
    nlinarith [Real.pi_gt_three]

theorem measurable_corrPsi : Measurable corrPsi := by
  unfold corrPsi corrPhi
  refine Measurable.ite measurableSet_Ico ?_ (by fun_prop)
  exact Measurable.ite (measurableSet_singleton 0) measurable_const (by fun_prop)

theorem dirichletPer_zero (N : ℕ) : dirichletPer N 0 = 2 * N + 1 := by
  unfold dirichletPer
  simp only [Complex.ofReal_zero, mul_zero, Complex.exp_zero, Finset.sum_const, Int.card_Icc,
    nsmul_eq_mul, mul_one]
  rw [show ((N : ℤ) + 1 - -(N : ℤ)) = ((2 * N + 1 : ℕ) : ℤ) by push_cast; ring, Int.toNat_natCast]
  push_cast; ring

/-- The kernel comparison: `1_{[−1/2,1/2)} D_N = D_{N+1/2} + ψ · sin((2N+1)π ·)`. -/
theorem indicator_dirichletPer_eq (N : ℕ) (z : ℝ) :
    (Set.Ico (-1 / 2 : ℝ) (1 / 2)).indicator (dirichletPer N) z =
      dirichletKernel (N + 1 / 2) z + (corrPsi z : ℂ) * (Real.sin ((2 * N + 1) * π * z) : ℂ) := by
  by_cases hz : z ∈ Set.Ico (-1 / 2 : ℝ) (1 / 2)
  · rw [Set.indicator_of_mem hz]
    simp only [corrPsi, ite_eq_left hz, corrPhi]
    by_cases h0 : z = 0
    · subst h0
      simp [dirichletPer_zero, dirichletKernel]; ring
    · rw [ite_eq_right h0]
      have hs : Real.sin (π * z) ≠ 0 := by
        have habs : |π * z| ≤ π / 2 := by
          rw [abs_mul, abs_of_pos Real.pi_pos]
          have : |z| ≤ 1 / 2 := abs_le.mpr ⟨by linarith [hz.1], hz.2.le⟩
          nlinarith [Real.pi_pos]
        intro h
        rw [Real.sin_eq_zero_iff_of_lt_of_lt (by
          rw [abs_le] at habs; linarith [Real.pi_pos]) (by
          rw [abs_le] at habs; linarith [Real.pi_pos])] at h
        exact h0 (by
          rcases mul_eq_zero.mp h with h | h
          · exact absurd h Real.pi_ne_zero
          · exact h)
      have hD := dirichletPer_mul_sin N z
      have hsC : (Real.sin (π * z) : ℂ) ≠ 0 := by exact_mod_cast hs
      have hDz : dirichletPer N z = (Real.sin ((2 * N + 1) * π * z) : ℂ) / (Real.sin (π * z) : ℂ) := by
        rw [eq_div_iff hsC, hD]
      rw [hDz]
      unfold dirichletKernel
      rw [ite_eq_right h0, show (2 * π * ((N : ℝ) + 1 / 2) * z : ℝ) = (2 * N + 1) * π * z by ring]
      generalize Real.sin ((2 * N + 1) * π * z) = a at *
      generalize Real.sin (π * z) = b at *
      have hπz : (π : ℂ) * z ≠ 0 := by exact_mod_cast mul_ne_zero Real.pi_ne_zero h0
      push_cast
      field_simp
      ring
  · rw [Set.indicator_of_notMem hz]
    have h0 : z ≠ 0 := by rintro rfl; exact hz ⟨by norm_num, by norm_num⟩
    simp only [corrPsi, ite_eq_right hz, dirichletKernel, ite_eq_right h0]
    rw [show (2 * π * ((N : ℝ) + 1 / 2) * z : ℝ) = (2 * N + 1) * π * z by ring]
    generalize Real.sin ((2 * N + 1) * π * z) = a
    push_cast
    have hπz : (π : ℂ) * z ≠ 0 := by exact_mod_cast mul_ne_zero Real.pi_ne_zero h0
    field_simp
    ring


/-! ### Step 7: localization -/

/-- The window `F_a = 1_{(a−1, a+2]} f`. -/
def window (f : ℝ → ℂ) (a : ℤ) : ℝ → ℂ := (Set.Ioc ((a : ℝ) - 1) (a + 2)).indicator f

theorem memLp_Ioc_shift {f : ℝ → ℂ} (hper : Function.Periodic f 1)
    (hf : MemLp f 2 (volume.restrict (Set.Ioc 0 1))) (k : ℤ) :
    MemLp ((Set.Ioc (k : ℝ) (k + 1)).indicator f) 2 volume := by
  have h0 : MemLp ((Set.Ioc (0 : ℝ) 1).indicator f) 2 volume :=
    (memLp_indicator_iff_restrict measurableSet_Ioc).mpr hf
  have h1 := h0.comp_measurePreserving (measurePreserving_sub_right volume (k : ℝ))
  refine h1.ae_eq (Filter.Eventually.of_forall fun x => ?_)
  simp only [Function.comp, Set.indicator_apply, Set.mem_Ioc]
  have hfx : f (x - k) = f x := by
    have := hper.sub_int_mul_eq (n := k) (x := x)
    simpa using this
  by_cases h : k < x ∧ x ≤ k + 1
  · rw [ite_eq_left ⟨by linarith [h.1], by linarith [h.2]⟩, ite_eq_left h, hfx]
  · rw [ite_eq_right (fun h' => h ⟨by linarith [h'.1], by linarith [h'.2]⟩), ite_eq_right h]

theorem memLp_window {f : ℝ → ℂ} (hper : Function.Periodic f 1)
    (hf : MemLp f 2 (volume.restrict (Set.Ioc 0 1))) (a : ℤ) : MemLp (window f a) 2 volume := by
  have hA : MemLp ((Set.Ioc ((a : ℝ) - 1) a).indicator f) 2 volume := by
    have := memLp_Ioc_shift hper hf (a - 1)
    push_cast at this; rwa [sub_add_cancel] at this
  have hB := memLp_Ioc_shift hper hf a
  have hC : MemLp ((Set.Ioc ((a : ℝ) + 1) (a + 2)).indicator f) 2 volume := by
    have := memLp_Ioc_shift hper hf (a + 1)
    push_cast at this; rwa [add_assoc, one_add_one_eq_two] at this
  have e1 : Set.Ioc ((a : ℝ) - 1) (a + 2) = Set.Ioc ((a : ℝ) - 1) (a + 1) ∪ Set.Ioc ((a : ℝ) + 1) (a + 2) :=
    (Set.Ioc_union_Ioc_eq_Ioc (by linarith) (by linarith)).symm
  have e2 : Set.Ioc ((a : ℝ) - 1) (a + 1) = Set.Ioc ((a : ℝ) - 1) a ∪ Set.Ioc (a : ℝ) (a + 1) :=
    (Set.Ioc_union_Ioc_eq_Ioc (by linarith) (by linarith)).symm
  unfold window
  rw [e1, Set.indicator_union_of_disjoint (Set.Ioc_disjoint_Ioc_of_le le_rfl), e2,
    Set.indicator_union_of_disjoint (Set.Ioc_disjoint_Ioc_of_le le_rfl)]
  exact (hA.add hB).add hC

theorem integrable_window {f : ℝ → ℂ} (hper : Function.Periodic f 1)
    (hf : MemLp f 2 (volume.restrict (Set.Ioc 0 1))) (a : ℤ) : Integrable (window f a) := by
  have h := (memLp_indicator_iff_restrict (measurableSet_Ioc (a := (a : ℝ) - 1) (b := a + 2))).mp
    (memLp_window hper hf a)
  have : IsFiniteMeasure (volume.restrict (Set.Ioc ((a : ℝ) - 1) (a + 2))) :=
    ⟨by simp⟩
  exact (integrable_indicator_iff measurableSet_Ioc).mpr (h.integrable (by norm_num))

theorem dirichletPer_sub_one (N : ℕ) (z : ℝ) : dirichletPer N (z - 1) = dirichletPer N z := by
  unfold dirichletPer
  refine Finset.sum_congr rfl fun k _ => ?_
  have : Complex.exp (2 * π * Complex.I * k * ↑(z - 1)) =
      Complex.exp (2 * π * Complex.I * k * z) * Complex.exp (-(k * (2 * π * Complex.I))) := by
    rw [← Complex.exp_add]; congr 1; push_cast; ring
  rw [this, Complex.exp_neg, Complex.exp_int_mul_two_pi_mul_I, inv_one, mul_one]

theorem intervalIntegrable_mul_dirichletPer {f : ℝ → ℂ}
    (hf : MemLp f 2 (volume.restrict (Set.Ioc 0 1))) (N : ℕ) (x : ℝ) :
    IntervalIntegrable (fun y => f y * dirichletPer N (x - y)) volume 0 1 := by
  have : IsFiniteMeasure (volume.restrict (Set.Ioc (0 : ℝ) 1)) := ⟨by simp⟩
  have hi : IntervalIntegrable f volume 0 1 :=
    (intervalIntegrable_iff_integrableOn_Ioc_of_le zero_le_one).mpr (hf.integrable (by norm_num))
  refine hi.mul_continuousOn ?_
  unfold dirichletPer
  exact (continuous_finsetSum _ fun k _ => by fun_prop).continuousOn

/-- `S_N f(x) = ∫_0^1 f(y) D_N(x − y) dy`. -/
theorem fourierPartialSum1_eq {f : ℝ → ℂ} (hf : MemLp f 2 (volume.restrict (Set.Ioc 0 1)))
    (N : ℕ) (x : ℝ) : fourierPartialSum1 f N x = ∫ y in (0 : ℝ)..1, f y * dirichletPer N (x - y) := by
  unfold fourierPartialSum1 fourierCoeff1 dirichletPer
  simp_rw [Finset.mul_sum]
  have : IsFiniteMeasure (volume.restrict (Set.Ioc (0 : ℝ) 1)) := ⟨by simp⟩
  have hi : IntervalIntegrable f volume 0 1 :=
    (intervalIntegrable_iff_integrableOn_Ioc_of_le zero_le_one).mpr (hf.integrable (by norm_num))
  rw [intervalIntegral.integral_finsetSum (fun k _ => hi.mul_continuousOn (by fun_prop))]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [← intervalIntegral.integral_mul_const]
  congr 1; funext y
  rw [mul_comm (Complex.exp _) (f y), mul_assoc, ← Complex.exp_add]
  congr 2; push_cast; ring

/-- Localization: on the window around `x ∈ (a, a+1)`,
`S_N f(x) = S_{N+1/2} F_a(x) + ∫ F_a(y) ψ(x−y) sin((2N+1)π(x−y)) dy`. -/
theorem fourierPartialSum1_eq_local {f : ℝ → ℂ} (hper : Function.Periodic f 1)
    (hf : MemLp f 2 (volume.restrict (Set.Ioc 0 1))) (a : ℤ) {x : ℝ}
    (hx : x ∈ Set.Ioo (a : ℝ) (a + 1)) (N : ℕ) :
    fourierPartialSum1 f N x = partialFourierIntegral (window f a) (N + 1 / 2) x +
      ∫ y, window f a y * ((corrPsi (x - y) : ℂ) * (Real.sin ((2 * N + 1) * π * (x - y)) : ℂ)) := by
  rw [fourierPartialSum1_eq hf]
  have hperφ : Function.Periodic (fun y => f y * dirichletPer N (x - y)) 1 := by
    intro y
    simp only
    rw [hper y, show x - (y + 1) = x - y - 1 by ring, dirichletPer_sub_one]
  have h1 := hperφ.intervalIntegral_add_eq 0 (x - 1 / 2)
  rw [zero_add] at h1
  rw [h1, intervalIntegral.integral_of_le (by linarith), ← integral_indicator measurableSet_Ioc]
  have hpt : ∀ y, (Set.Ioc (x - 1 / 2) (x - 1 / 2 + 1)).indicator
      (fun y => f y * dirichletPer N (x - y)) y =
      window f a y * dirichletKernel (N + 1 / 2) (x - y) +
        window f a y * ((corrPsi (x - y) : ℂ) * (Real.sin ((2 * N + 1) * π * (x - y)) : ℂ)) := by
    intro y
    rw [← mul_add, ← indicator_dirichletPer_eq]
    simp only [window, Set.indicator_apply, Set.mem_Ioc, Set.mem_Ico]
    by_cases hy : x - 1 / 2 < y ∧ y ≤ x - 1 / 2 + 1
    · have hw : (a : ℝ) - 1 < y ∧ y ≤ a + 2 := ⟨by linarith [hx.1, hy.1], by linarith [hx.2, hy.2]⟩
      rw [ite_eq_left hy, ite_eq_left hw, ite_eq_left ⟨by linarith [hy.2], by linarith [hy.1]⟩]
    · rw [ite_eq_right hy, ite_eq_right (show ¬(-1 / 2 ≤ x - y ∧ x - y < 1 / 2) from
        fun h => hy ⟨by linarith [h.2], by linarith [h.1]⟩), mul_zero]
  simp_rw [hpt]
  have hint2 : Integrable fun y => window f a y *
      ((corrPsi (x - y) : ℂ) * (Real.sin ((2 * N + 1) * π * (x - y)) : ℂ)) := by
    refine (integrable_window hper hf a).mul_bdd (c := 1) ?_ (Filter.Eventually.of_forall fun y => ?_)
    · exact ((Complex.measurable_ofReal.comp (measurable_corrPsi.comp
        (measurable_const.sub measurable_id))).mul (by fun_prop)).aestronglyMeasurable
    · rw [norm_mul, Complex.norm_real, Complex.norm_real, Real.norm_eq_abs, Real.norm_eq_abs]
      exact (mul_le_mul (abs_corrPsi_le _) (Real.abs_sin_le_one _) (abs_nonneg _) zero_le_one).trans
        (by norm_num)
  rw [integral_add (integrable_mul_dirichletKernel (memLp_window hper hf a) (by positivity) x) hint2]
  rfl


/-- Riemann–Lebesgue: `∫ H(y) sin((2N+1)π(x−y)) dy → 0`. -/
theorem tendsto_integral_mul_sin {H : ℝ → ℂ} (hH : Integrable H) (x : ℝ) :
    Tendsto (fun N : ℕ => ∫ y, H y * (Real.sin ((2 * N + 1) * π * (x - y)) : ℂ)) atTop (𝓝 0) := by
  set A : ℝ → ℂ := fun w => ∫ y, 𝐞 (-(y * w)) • H y
  have hRL : Tendsto A (Filter.cocompact ℝ) (𝓝 0) := Real.tendsto_integral_exp_smul_cocompact H
  have hw : Tendsto (fun N : ℕ => (N : ℝ) + 1 / 2) atTop atTop :=
    tendsto_natCast_atTop_atTop.atTop_add tendsto_const_nhds
  have h1 : Tendsto (fun N : ℕ => A ((N : ℝ) + 1 / 2)) atTop (𝓝 0) :=
    hRL.comp (hw.mono_right atTop_le_cocompact)
  have h2 : Tendsto (fun N : ℕ => A (-((N : ℝ) + 1 / 2))) atTop (𝓝 0) :=
    hRL.comp ((tendsto_neg_atTop_atBot.comp hw).mono_right atBot_le_cocompact)
  have hchar : ∀ w, Integrable fun y => 𝐞 (-(y * w)) • H y := fun w =>
    hH.norm.mono' ((by fun_prop : Continuous fun y : ℝ => 𝐞 (-(y * w))).aestronglyMeasurable.smul
      hH.aestronglyMeasurable) (Filter.Eventually.of_forall fun y => by rw [Circle.norm_smul])
  have key : ∀ N : ℕ, ∫ y, H y * (Real.sin ((2 * N + 1) * π * (x - y)) : ℂ) =
      Complex.I / 2 * (Complex.exp (-(↑(2 * π * ((N : ℝ) + 1 / 2) * x) * Complex.I)) *
          A (-((N : ℝ) + 1 / 2)) -
        Complex.exp (↑(2 * π * ((N : ℝ) + 1 / 2) * x) * Complex.I) * A ((N : ℝ) + 1 / 2)) := by
    intro N
    simp only [A]
    rw [← integral_const_mul, ← integral_const_mul, ← integral_sub
      ((hchar _).const_mul _) ((hchar _).const_mul _), ← integral_const_mul]
    congr 1; funext y
    rw [Complex.ofReal_sin, Complex.sin, Circle.smul_def, Circle.smul_def, smul_eq_mul, smul_eq_mul,
      Real.fourierChar_apply, Real.fourierChar_apply]
    have e1 : Complex.exp (-↑((2 * N + 1) * π * (x - y)) * Complex.I) =
        Complex.exp (-(↑(2 * π * ((N : ℝ) + 1 / 2) * x) * Complex.I)) *
          Complex.exp (↑(2 * π * -(y * -((N : ℝ) + 1 / 2))) * Complex.I) := by
      rw [← Complex.exp_add]; congr 1; push_cast; ring
    have e2 : Complex.exp (↑((2 * N + 1) * π * (x - y)) * Complex.I) =
        Complex.exp (↑(2 * π * ((N : ℝ) + 1 / 2) * x) * Complex.I) *
          Complex.exp (↑(2 * π * -(y * ((N : ℝ) + 1 / 2))) * Complex.I) := by
      rw [← Complex.exp_add]; congr 1; push_cast; ring
    rw [e1, e2]
    ring
  simp_rw [key]
  refine squeeze_zero_norm (fun N => ?_) ((h2.norm.add h1.norm).trans (by simp))
  have ha : ‖Complex.exp (-(↑(2 * π * ((N : ℝ) + 1 / 2) * x) * Complex.I))‖ = 1 := by
    rw [show -(↑(2 * π * ((N : ℝ) + 1 / 2) * x) * Complex.I) =
      ↑(-(2 * π * ((N : ℝ) + 1 / 2) * x)) * Complex.I by push_cast; ring,
      Complex.norm_exp_ofReal_mul_I]
  have hb : ‖Complex.exp (↑(2 * π * ((N : ℝ) + 1 / 2) * x) * Complex.I)‖ = 1 :=
    Complex.norm_exp_ofReal_mul_I _
  have hI : ‖Complex.I / 2‖ ≤ 1 := by simp; norm_num
  rw [norm_mul]
  refine (mul_le_of_le_one_left (norm_nonneg _) hI).trans ?_
  refine (norm_sub_le _ _).trans (le_of_eq ?_)
  rw [norm_mul, norm_mul, ha, hb, one_mul, one_mul]

/-- **Carleson's theorem** (1966): for a `1`-periodic `f : ℝ → ℂ` that is square integrable on a
period (`MemLp f 2` on `(0,1]`), the symmetric partial sums `∑_{|k|≤N} f̂(k) e^{2πikx}` of its Fourier
series converge to `f(x)` for almost every `x ∈ ℝ`. -/
theorem carleson_fourierSeries {f : ℝ → ℂ} (hper : Function.Periodic f 1)
    (hf : MemLp f 2 (volume.restrict (Set.Ioc 0 1))) :
    ∀ᵐ x, Tendsto (fun N => fourierPartialSum1 f N x) atTop (𝓝 (f x)) := by
  have hA : ∀ a : ℤ, ∀ᵐ x, Tendsto (fun R => partialFourierIntegral (window f a) R x) atTop
      (𝓝 (window f a x)) := fun a => carleson_real_line (memLp_window hper hf a)
  rw [← ae_all_iff] at hA
  have hZ : ∀ᵐ x : ℝ, x ∉ Set.range (Int.cast : ℤ → ℝ) := (Set.countable_range _).ae_notMem volume
  filter_upwards [hA, hZ] with x hx hxZ
  set a := ⌊x⌋
  have hax : (a : ℝ) < x := lt_of_le_of_ne (Int.floor_le x) (fun h => hxZ ⟨a, h⟩)
  have hxa : x ∈ Set.Ioo (a : ℝ) (a + 1) := ⟨hax, Int.lt_floor_add_one x⟩
  have hwin : window f a x = f x :=
    Set.indicator_of_mem (show x ∈ Set.Ioc ((a : ℝ) - 1) (a + 2) from
      ⟨by linarith [hxa.1], by linarith [hxa.2]⟩) f
  have hR : Tendsto (fun N : ℕ => (N : ℝ) + 1 / 2) atTop atTop :=
    tendsto_natCast_atTop_atTop.atTop_add tendsto_const_nhds
  have h1 := (hx a).comp hR
  rw [hwin] at h1
  set H : ℝ → ℂ := fun y => window f a y * (corrPsi (x - y) : ℂ)
  have hH : Integrable H := by
    refine (integrable_window hper hf a).mul_bdd (c := 1) ?_ (Filter.Eventually.of_forall fun y => ?_)
    · exact (Complex.measurable_ofReal.comp (measurable_corrPsi.comp
        (measurable_const.sub measurable_id))).aestronglyMeasurable
    · rw [Complex.norm_real, Real.norm_eq_abs]; exact abs_corrPsi_le _
  have h2 := tendsto_integral_mul_sin hH x
  have h3 := h1.add h2
  rw [add_zero] at h3
  refine h3.congr fun N => ?_
  rw [fourierPartialSum1_eq_local hper hf a hxa N]
  simp only [Function.comp, H, mul_assoc]

/-! ### Carleson's theorem for `2π`-periodic functions (Mathlib's Fourier coefficients) -/

theorem memLp_comp_mul_left {φ : ℝ → ℂ} (hφ : MemLp φ 2 volume) {c : ℝ} (hc : c ≠ 0) :
    MemLp (fun x => φ (c * x)) 2 volume := by
  have h1 : MemLp φ 2 (Measure.map (c * ·) volume) := by
    rw [Real.map_volume_mul_left hc]; exact hφ.smul_measure ENNReal.ofReal_ne_top
  exact (memLp_map_measure_iff h1.aestronglyMeasurable
    (measurable_const_mul c).aemeasurable).mp h1

/-- The rescaling `t ↦ f(2πt)` of `f ∈ L²[0, 2π)` is square integrable on `(0, 1]`. -/
theorem memLp_rescale {f : ℝ → ℂ} (hf : MemLp f 2 (volume.restrict (Set.Ico 0 (2 * π)))) :
    MemLp (fun t => f (2 * π * t)) 2 (volume.restrict (Set.Ioc 0 1)) := by
  have hπ : (0 : ℝ) < 2 * π := by positivity
  have h0 : MemLp ((Set.Ico 0 (2 * π)).indicator f) 2 volume :=
    (memLp_indicator_iff_restrict measurableSet_Ico).mpr hf
  have hG : MemLp ((Set.Ico (0 : ℝ) 1).indicator fun t => f (2 * π * t)) 2 volume := by
    refine (memLp_comp_mul_left h0 hπ.ne').ae_eq (Eventually.of_forall fun t => ?_)
    have e1 : 0 ≤ 2 * π * t ↔ 0 ≤ t := by
      constructor <;> intro h <;> nlinarith [Real.pi_pos]
    have e2 : 2 * π * t < 2 * π ↔ t < 1 := by
      constructor <;> intro h <;> nlinarith [Real.pi_pos]
    simp only [Set.indicator_apply, Set.mem_Ico, e1, e2]
  rw [← Measure.restrict_congr_set Ico_ae_eq_Ioc]
  exact (memLp_indicator_iff_restrict measurableSet_Ico).mp hG

/-- Mathlib's Fourier coefficients on `[0, 2π]` are those of the rescaled function. -/
theorem fourierCoeffOn_eq_fourierCoeff1 (f : ℝ → ℂ) (n : ℤ) :
    fourierCoeffOn Real.two_pi_pos f n = fourierCoeff1 (fun t => f (2 * π * t)) n := by
  have hπ : (2 * π : ℝ) ≠ 0 := by positivity
  have hπC : (2 * π : ℂ) ≠ 0 := by exact_mod_cast hπ
  rw [fourierCoeffOn_eq_integral]
  unfold fourierCoeff1
  have h1 : (∫ y in (0 : ℝ)..1, Complex.exp (-(2 * π * Complex.I * n * y)) * f (2 * π * y)) =
      ∫ y in (0 : ℝ)..1,
        (fun u : ℝ => Complex.exp (-(Complex.I * n * u)) * f u) (2 * π * y) := by
    congr 1; funext y; simp only; congr 2; push_cast; ring
  rw [h1, intervalIntegral.integral_comp_mul_left
    (f := fun u : ℝ => Complex.exp (-(Complex.I * n * u)) * f u) hπ, mul_zero, mul_one, sub_zero]
  simp_rw [fourier_coe_apply, smul_eq_mul]
  rw [Complex.real_smul, Complex.real_smul]
  congr 1
  · push_cast; ring
  · congr 1; funext x; congr 2; push_cast; field_simp

theorem fourierPartialSum_eq_fourierPartialSum1 (f : ℝ → ℂ) (N : ℕ) (x : ℝ) :
    ∑ n ∈ Finset.Icc (-(N : ℤ)) N,
        fourierCoeffOn Real.two_pi_pos f n * fourier n (x : AddCircle (2 * π)) =
      fourierPartialSum1 (fun t => f (2 * π * t)) N ((2 * π)⁻¹ * x) := by
  have hπC : (2 * π : ℂ) ≠ 0 := by exact_mod_cast (by positivity : (2 * π : ℝ) ≠ 0)
  unfold fourierPartialSum1
  refine Finset.sum_congr rfl fun n _ => ?_
  rw [fourierCoeffOn_eq_fourierCoeff1, fourier_coe_apply]
  congr 2
  push_cast
  field_simp

/-- **Carleson's theorem** (Carleson 1966): the Fourier series of a `2π`-periodic function on `ℝ`
that is square integrable on `[0, 2π)` converges to it almost everywhere. -/
theorem classical_carleson (f : ℝ → ℂ) (hper : Function.Periodic f (2 * π))
    (hf : MemLp f 2 (volume.restrict (Set.Ico 0 (2 * π)))) :
    ∀ᵐ x : ℝ, Tendsto (fun N : ℕ => ∑ n ∈ Finset.Icc (-(N : ℤ)) N,
      fourierCoeffOn Real.two_pi_pos f n * fourier n (x : AddCircle (2 * π))) atTop (𝓝 (f x)) := by
  have hπ : (2 * π : ℝ) ≠ 0 := by positivity
  set g : ℝ → ℂ := fun t => f (2 * π * t)
  have hgper : Function.Periodic g 1 := fun t => by
    simp only [g]; rw [mul_add, mul_one, hper]
  have h := carleson_fourierSeries hgper (memLp_rescale hf)
  rw [ae_iff] at h ⊢
  have hset : {x : ℝ | ¬ Tendsto (fun N : ℕ => ∑ n ∈ Finset.Icc (-(N : ℤ)) N,
      fourierCoeffOn Real.two_pi_pos f n * fourier n (x : AddCircle (2 * π))) atTop (𝓝 (f x))} =
      (fun x => (2 * π)⁻¹ * x) ⁻¹'
        {t | ¬ Tendsto (fun N => fourierPartialSum1 g N t) atTop (𝓝 (g t))} := by
    ext x
    simp only [Set.mem_ofPred_eq, Set.mem_preimage, g]
    rw [mul_inv_cancel_left₀ hπ]
    simp_rw [fourierPartialSum_eq_fourierPartialSum1]
  rw [hset, Real.volume_preimage_mul_left (inv_ne_zero hπ), h, mul_zero]

end Auto
