/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/
import Mathlib

/-!
# The Hardy–Littlewood maximal theorem for a homogeneous gauge

Let `E` be a topological additive group carrying a translation-invariant measure `μ`, and let
`ρ : E → ℝ` be a *homogeneous gauge*: a continuous, nonnegative, symmetric and subadditive function
with `ρ(0) = 0`
whose balls `{ρ ≤ r}` have measure `r^D μ{ρ ≤ 1}` for some `D > 0` (for instance an anisotropic
norm on `ℝⁿ` with Lebesgue measure, where `D` is the homogeneous dimension). For
`g : E → [0, ∞]` and `λ ≥ 0` the (centered, restricted) maximal function is
`M_λ g(x) = sup_{r ≥ λ} μ(B(x,r))⁻¹ ∫_{B(x,r)} g`, `B(x,r) = {y : ρ(x - y) ≤ r}`
(the supremum is taken over rational radii, which gives the same value).

**Theorem (Hardy–Littlewood maximal theorem).**
* (weak type `(1,1)`) `μ{M_0 g > t} ≤ 3^D t⁻¹ ∫ g` for every `t > 0`;
* (strong type `(2,2)`) `∫ (M_0 g)² ≤ C ∫ g²` with `C` depending only on `D`.

**Theorem (majorization of approximate identities).** If `W : ℝ → [0, ∞]` is antitone and
constant on `[0, λ]`, then `∫ g(x - y) W(ρ(y)) dy ≤ (∫ W(ρ(y)) dy) M_λ g(x)`.

The weak type bound follows from the Vitali covering lemma (Mathlib's
`Vitali.exists_disjoint_subfamily_covering_enlargement`) and the doubling property
`μ(B(x,3r)) = 3^D μ(B(x,r))`. The `L²` bound follows from the weak type bound by the layer cake
formula (Marcinkiewicz interpolation). The majorization follows from the layer cake decomposition
of `W ∘ ρ` into gauge balls.

## References

* E. M. Stein, *Harmonic Analysis: Real-Variable Methods, Orthogonality, and Oscillatory
  Integrals*, Princeton University Press, 1993, Chapter I (maximal functions on spaces of
  homogeneous type).
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., Graduate Texts in Mathematics 249,
  Springer, 2014, Section 2.1 (the Hardy–Littlewood maximal operator and control of approximate
  identities by it).
-/

noncomputable section

open MeasureTheory Set
open scoped ENNReal NNReal

namespace Auto

/-- A homogeneous gauge on an additive group with measure `μ`: a continuous, nonnegative, symmetric,
subadditive function whose balls have measure `r^D μ{ρ ≤ 1}`. -/
structure HomGauge (E : Type*) [AddCommGroup E] [TopologicalSpace E] [MeasurableSpace E]
    (μ : Measure E) where
  /-- The gauge. -/
  ρ : E → ℝ
  continuous : Continuous ρ
  nonneg : ∀ x, 0 ≤ ρ x
  zero : ρ 0 = 0
  neg : ∀ x, ρ (-x) = ρ x
  add_le : ∀ x y, ρ (x + y) ≤ ρ x + ρ y
  /-- The homogeneous dimension. -/
  D : ℝ
  D_pos : 0 < D
  vol : ∀ r : ℝ, 0 < r → μ {y | ρ y ≤ r} = ENNReal.ofReal (r ^ D) * μ {y | ρ y ≤ 1}
  vol_pos : 0 < μ {y | ρ y ≤ 1}
  vol_lt_top : μ {y | ρ y ≤ 1} < ⊤

namespace HomGauge

variable {E : Type*} [AddCommGroup E] [TopologicalSpace E] [IsTopologicalAddGroup E]
  [MeasurableSpace E] [BorelSpace E] [SecondCountableTopology E]
  {μ : Measure E} [μ.IsAddLeftInvariant] [SFinite μ] (G : HomGauge E μ)

/-- The closed gauge ball `B(x, r) = {y : ρ(x - y) ≤ r}`. -/
def ball (x : E) (r : ℝ) : Set E := {y | G.ρ (x - y) ≤ r}

omit [IsTopologicalAddGroup E] [BorelSpace E] [SecondCountableTopology E]
  [μ.IsAddLeftInvariant] [SFinite μ] in
theorem ball_eq_preimage (x : E) (r : ℝ) :
    G.ball x r = (fun y => -x + y) ⁻¹' {z | G.ρ z ≤ r} := by
  ext y
  simp only [ball, mem_ofPred_eq, mem_preimage]
  rw [← G.neg (x - y), neg_sub, sub_eq_neg_add]

omit [SecondCountableTopology E] [μ.IsAddLeftInvariant] [SFinite μ] in
theorem measurableSet_ball (x : E) (r : ℝ) : MeasurableSet (G.ball x r) :=
  (isClosed_le (G.continuous.comp (continuous_const.sub continuous_id)) continuous_const).measurableSet

omit [SecondCountableTopology E] [SFinite μ] in
theorem measure_ball (x : E) (r : ℝ) : μ (G.ball x r) = μ {z | G.ρ z ≤ r} := by
  rw [ball_eq_preimage, measure_preimage_add]

omit [SecondCountableTopology E] [SFinite μ] in
theorem measure_ball_eq (x : E) {r : ℝ} (hr : 0 < r) :
    μ (G.ball x r) = ENNReal.ofReal (r ^ G.D) * μ {y | G.ρ y ≤ 1} := by
  rw [measure_ball, G.vol r hr]

omit [SecondCountableTopology E] [SFinite μ] in
theorem measure_ball_pos (x : E) {r : ℝ} (hr : 0 < r) : 0 < μ (G.ball x r) := by
  rw [G.measure_ball_eq x hr]
  exact ENNReal.mul_pos (by simpa using Real.rpow_pos_of_pos hr G.D) G.vol_pos.ne'

omit [SecondCountableTopology E] [SFinite μ] in
theorem measure_ball_lt_top (x : E) {r : ℝ} (hr : 0 < r) : μ (G.ball x r) < ⊤ := by
  rw [G.measure_ball_eq x hr]
  exact ENNReal.mul_lt_top ENNReal.ofReal_lt_top G.vol_lt_top

omit [SecondCountableTopology E] [SFinite μ] in
theorem measure_ball_mul (x : E) {c r : ℝ} (hc : 0 < c) (hr : 0 < r) :
    μ (G.ball x (c * r)) = ENNReal.ofReal (c ^ G.D) * μ (G.ball x r) := by
  rw [G.measure_ball_eq x (mul_pos hc hr), G.measure_ball_eq x hr, ← mul_assoc,
    ← ENNReal.ofReal_mul (by positivity), Real.mul_rpow hc.le hr.le]

omit [IsTopologicalAddGroup E] [BorelSpace E] [SecondCountableTopology E]
  [μ.IsAddLeftInvariant] [SFinite μ] in
theorem ball_mono (x : E) {r s : ℝ} (h : r ≤ s) : G.ball x r ⊆ G.ball x s :=
  fun _ hy => le_trans hy h

omit [IsTopologicalAddGroup E] [BorelSpace E] [SecondCountableTopology E]
  [μ.IsAddLeftInvariant] [SFinite μ] in
theorem mem_ball_self (x : E) {r : ℝ} (hr : 0 ≤ r) : x ∈ G.ball x r := by
  simp [ball, G.zero, hr]

/-- The maximal function `M_λ g(x) = sup_{q ≥ λ, q > 0 rational} μ(B(x,q))⁻¹ ∫_{B(x,q)} g`. -/
def maximal (lam : ℝ) (g : E → ℝ≥0∞) (x : E) : ℝ≥0∞ :=
  ⨆ (q : ℚ) (_ : lam ≤ q) (_ : 0 < q), (μ (G.ball 0 q))⁻¹ * ∫⁻ y in G.ball x q, g y ∂μ

omit [SecondCountableTopology E] [SFinite μ] in
theorem measure_ball_zero (x : E) (r : ℝ) : μ (G.ball x r) = μ (G.ball 0 r) := by
  rw [G.measure_ball, G.measure_ball]

omit [SecondCountableTopology E] [SFinite μ] in
theorem le_maximal (lam : ℝ) (g : E → ℝ≥0∞) (x : E) {q : ℚ} (hlq : lam ≤ q) (hq : 0 < q) :
    (μ (G.ball x q))⁻¹ * ∫⁻ y in G.ball x q, g y ∂μ ≤ G.maximal lam g x := by
  rw [G.measure_ball_zero x]
  exact le_iSup₂_of_le q hlq (le_iSup_of_le hq le_rfl)

omit [SecondCountableTopology E] [SFinite μ] in
theorem maximal_anti (g : E → ℝ≥0∞) (x : E) {lam lam' : ℝ} (h : lam ≤ lam') :
    G.maximal lam' g x ≤ G.maximal lam g x :=
  iSup₂_le fun q hq => iSup_le fun hq0 => G.le_maximal lam g x (h.trans hq) hq0 |>.trans'
    (by rw [G.measure_ball_zero x])

omit [μ.IsAddLeftInvariant] in
theorem measurable_maximal (lam : ℝ) {g : E → ℝ≥0∞} (hg : Measurable g) :
    Measurable (G.maximal lam g) := by
  refine Measurable.iSup fun q => Measurable.iSup fun _ => Measurable.iSup fun _ => ?_
  refine Measurable.const_mul ?_ _
  have hS : MeasurableSet {p : E × E | G.ρ (p.1 - p.2) ≤ q} :=
    (isClosed_le (G.continuous.comp (continuous_fst.sub continuous_snd))
      continuous_const).measurableSet
  have hF : Measurable (fun p : E × E => {p : E × E | G.ρ (p.1 - p.2) ≤ q}.indicator
      (fun p => g p.2) p) := (hg.comp measurable_snd).indicator hS
  have := hF.lintegral_prod_right' (ν := μ)
  have e : (fun x => ∫⁻ y in G.ball x q, g y ∂μ) = fun x => ∫⁻ y,
      {p : E × E | G.ρ (p.1 - p.2) ≤ q}.indicator (fun p => g p.2) (x, y) ∂μ := by
    funext x
    rw [← lintegral_indicator (G.measurableSet_ball x q)]
    rfl
  rw [e]
  exact this

omit [IsTopologicalAddGroup E] [BorelSpace E] [SecondCountableTopology E]
  [μ.IsAddLeftInvariant] [SFinite μ] in
theorem mem_ball_comm {x y : E} {r : ℝ} : y ∈ G.ball x r ↔ x ∈ G.ball y r := by
  simp only [ball, mem_ofPred_eq]
  rw [← G.neg (x - y), neg_sub]

omit [IsTopologicalAddGroup E] [BorelSpace E] [SecondCountableTopology E]
  [μ.IsAddLeftInvariant] [SFinite μ] in
theorem ball_subset_of_inter (a b : E) {qa qb : ℝ} (h : (G.ball a qa ∩ G.ball b qb).Nonempty) :
    a ∈ G.ball b (qa + qb) := by
  obtain ⟨z, hza, hzb⟩ := h
  simp only [ball, mem_ofPred_eq] at hza hzb ⊢
  have h1 := G.add_le (b - z) (z - a)
  rw [sub_add_sub_cancel] at h1
  have h2 : G.ρ (z - a) = G.ρ (a - z) := by rw [← G.neg (a - z), neg_sub]
  linarith

omit [SecondCountableTopology E] in
/-- **Weak type `(1,1)` of the maximal function**: `μ{M_0 g > t} ≤ 3^D t⁻¹ ∫ g`. -/
theorem measure_maximal_gt_le (g : E → ℝ≥0∞) {t : ℝ≥0∞} (ht0 : t ≠ 0) :
    μ {x | t < G.maximal 0 g x} ≤ ENNReal.ofReal (3 ^ G.D) / t * ∫⁻ y, g y ∂μ := by
  by_cases htop : t = ⊤
  · subst htop; simp
  by_cases hint : ∫⁻ y, g y ∂μ = ⊤
  · rw [hint, ENNReal.mul_top]
    · exact le_top
    · exact (ENNReal.div_pos (by simpa using Real.rpow_pos_of_pos (by norm_num : (0 : ℝ) < 3) G.D)
        htop).ne'
  set A := {x | t < G.maximal 0 g x}
  -- choose a good radius for each point of `A`
  have hex : ∀ x ∈ A, ∃ q : ℚ, 0 < q ∧
      t < (μ (G.ball x q))⁻¹ * ∫⁻ y in G.ball x q, g y ∂μ := by
    intro x hx
    simp only [A, mem_ofPred_eq, maximal, lt_iSup_iff] at hx
    obtain ⟨q, -, hq, h⟩ := hx
    exact ⟨q, hq, by rwa [G.measure_ball_zero x]⟩
  choose! qx hqpos hqgood using hex
  have hball : ∀ x ∈ A, t * μ (G.ball x (qx x)) ≤ ∫⁻ y in G.ball x (qx x), g y ∂μ := by
    intro x hx
    have hpos := G.measure_ball_pos x (by exact_mod_cast hqpos x hx : (0 : ℝ) < qx x)
    have hfin := G.measure_ball_lt_top x (by exact_mod_cast hqpos x hx : (0 : ℝ) < qx x)
    have h := (hqgood x hx).le
    rw [← ENNReal.div_eq_inv_mul, ENNReal.le_div_iff_mul_le (Or.inl hpos.ne') (Or.inl hfin.ne)] at h
    exact h
  -- the radii are bounded
  set v := μ {y | G.ρ y ≤ 1}
  set K : ℝ := ((∫⁻ y, g y ∂μ) / (t * v)).toReal
  have hqR : ∀ x ∈ A, (qx x : ℝ) ≤ (K + 1) ^ (1 / G.D) := by
    intro x hx
    have hq : (0 : ℝ) < qx x := by exact_mod_cast hqpos x hx
    have h1 := (hball x hx).trans (setLIntegral_le_lintegral _ _)
    rw [G.measure_ball_eq x hq] at h1
    have htv : t * v ≠ 0 := mul_ne_zero ht0 G.vol_pos.ne'
    have htv' : t * v ≠ ⊤ := ENNReal.mul_ne_top htop G.vol_lt_top.ne
    have h2 : ENNReal.ofReal ((qx x : ℝ) ^ G.D) ≤ (∫⁻ y, g y ∂μ) / (t * v) := by
      rw [ENNReal.le_div_iff_mul_le (Or.inl htv) (Or.inl htv')]
      calc ENNReal.ofReal ((qx x : ℝ) ^ G.D) * (t * v)
          = t * (ENNReal.ofReal ((qx x : ℝ) ^ G.D) * v) := by ring
        _ ≤ _ := h1
    have hfin : (∫⁻ y, g y ∂μ) / (t * v) ≠ ⊤ := ENNReal.div_ne_top hint htv
    have h3 : (qx x : ℝ) ^ G.D ≤ K := by
      rw [← ENNReal.ofReal_le_iff_le_toReal hfin]; exact h2
    calc (qx x : ℝ) = ((qx x : ℝ) ^ G.D) ^ (1 / G.D) := by
          rw [← Real.rpow_mul hq.le, mul_one_div_cancel G.D_pos.ne', Real.rpow_one]
      _ ≤ (K + 1) ^ (1 / G.D) := Real.rpow_le_rpow (by positivity) (by linarith)
          (by have := G.D_pos; positivity)
  -- Vitali
  obtain ⟨u, huA, hud, hcov⟩ := Vitali.exists_disjoint_subfamily_covering_enlargement
    (fun x => G.ball x (qx x)) A (fun x => (qx x : ℝ)) 2 (by norm_num)
    (fun x hx => by exact_mod_cast (hqpos x hx).le) _ hqR
    (fun x hx => ⟨x, G.mem_ball_self x (by exact_mod_cast (hqpos x hx).le)⟩)
  have hcount : u.Countable := by
    have h := Measure.countable_meas_pos_of_disjoint_iUnion (μ := μ)
      (As := fun b : u => G.ball b (qx b)) (fun b => G.measurableSet_ball _ _)
      (fun b b' hbb' => hud b.2 b'.2 (fun h => hbb' (Subtype.ext h)))
    have : {b : u | 0 < μ (G.ball b (qx b))} = univ := by
      ext b
      simp only [mem_ofPred_eq, mem_univ, iff_true]
      exact G.measure_ball_pos _ (by exact_mod_cast hqpos b (huA b.2))
    rw [this] at h
    exact Set.countable_coe_iff.mp (countable_univ_iff.mp h)
  have hsubset : A ⊆ ⋃ b ∈ u, G.ball b (3 * qx b) := by
    intro a ha
    obtain ⟨b, hbu, hinter, hle⟩ := hcov a ha
    refine mem_biUnion hbu ?_
    have := G.ball_subset_of_inter a b hinter
    exact G.ball_mono b (by linarith) this
  have := hcount.to_subtype
  calc μ A ≤ μ (⋃ b ∈ u, G.ball b (3 * qx b)) := measure_mono hsubset
    _ ≤ ∑' b : u, μ (G.ball b (3 * qx b)) := measure_biUnion_le _ hcount _
    _ = ∑' b : u, ENNReal.ofReal (3 ^ G.D) * μ (G.ball b (qx b)) := by
        congr 1; ext b
        exact G.measure_ball_mul _ (by norm_num) (by exact_mod_cast hqpos b (huA b.2))
    _ ≤ ∑' b : u, ENNReal.ofReal (3 ^ G.D) / t * ∫⁻ y in G.ball b (qx b), g y ∂μ := by
        refine ENNReal.tsum_le_tsum fun b => ?_
        have h := hball b (huA b.2)
        have hB : μ (G.ball b (qx b)) ≤ (∫⁻ y in G.ball b (qx b), g y ∂μ) / t :=
          (ENNReal.le_div_iff_mul_le (Or.inl ht0) (Or.inl htop)).mpr (by rwa [mul_comm])
        calc ENNReal.ofReal (3 ^ G.D) * μ (G.ball b (qx b))
            ≤ ENNReal.ofReal (3 ^ G.D) * ((∫⁻ y in G.ball b (qx b), g y ∂μ) / t) :=
              mul_le_mul_right hB _
          _ = _ := by rw [ENNReal.div_eq_inv_mul, ENNReal.div_eq_inv_mul]; ring
    _ = ENNReal.ofReal (3 ^ G.D) / t * ∫⁻ y in ⋃ b : u, G.ball b (qx b), g y ∂μ := by
        rw [ENNReal.tsum_mul_left, lintegral_iUnion (s := fun b : u => G.ball (b : E) (qx b))
          (fun b => G.measurableSet_ball _ _)
          (fun b b' hbb' => hud b.2 b'.2 (fun h => hbb' (Subtype.ext h)))]
    _ ≤ _ := mul_le_mul_right (setLIntegral_le_lintegral _ _) _

end HomGauge

theorem lintegral_Ioi_indicator_two_mul (a : ℝ≥0∞) :
    ∫⁻ t in Ioi (0 : ℝ), {t : ℝ | ENNReal.ofReal t < a}.indicator
      (fun t => ENNReal.ofReal (2 * t)) t = a ^ 2 := by
  have hmeas : MeasurableSet {t : ℝ | ENNReal.ofReal t < a} :=
    measurableSet_lt ENNReal.measurable_ofReal measurable_const
  rw [lintegral_indicator hmeas, Measure.restrict_restrict hmeas]
  rcases eq_or_ne a ⊤ with rfl | ha
  · have : {t : ℝ | ENNReal.ofReal t < ⊤} ∩ Ioi 0 = Ioi 0 := by ext t; simp
    rw [this, ENNReal.top_pow two_ne_zero, eq_top_iff]
    calc (⊤ : ℝ≥0∞) = ∫⁻ t in Ioi (1 : ℝ), 2 ∂volume := by
          rw [setLIntegral_const, Real.volume_Ioi, ENNReal.mul_top two_ne_zero]
      _ ≤ ∫⁻ t in Ioi (0 : ℝ), ENNReal.ofReal (2 * t) := by
          refine le_trans (setLIntegral_mono' measurableSet_Ioi fun t ht => ?_)
            (lintegral_mono_set (Ioi_subset_Ioi zero_le_one))
          have : (1 : ℝ) < t := ht
          rw [show (2 : ℝ≥0∞) = ENNReal.ofReal 2 by simp]
          exact ENNReal.ofReal_le_ofReal (by linarith)
  · have hset : {t : ℝ | ENNReal.ofReal t < a} ∩ Ioi 0 = Ioo 0 a.toReal := by
      ext t
      simp only [mem_inter_iff, mem_ofPred_eq, mem_Ioi, mem_Ioo]
      constructor
      · rintro ⟨h1, h2⟩
        exact ⟨h2, (ENNReal.ofReal_lt_iff_lt_toReal h2.le ha).mp h1⟩
      · rintro ⟨h1, h2⟩
        exact ⟨(ENNReal.ofReal_lt_iff_lt_toReal h1.le ha).mpr h2, h1⟩
    rw [hset, ← ofReal_integral_eq_lintegral_ofReal]
    · rw [← integral_Ioc_eq_integral_Ioo, ← intervalIntegral.integral_of_le ENNReal.toReal_nonneg]
      rw [intervalIntegral.integral_const_mul, integral_id]
      rw [← ENNReal.ofReal_toReal ha, ← ENNReal.ofReal_pow ENNReal.toReal_nonneg,
        ENNReal.toReal_ofReal ENNReal.toReal_nonneg]
      congr 1; ring
    · exact (continuous_const.mul continuous_id).integrableOn_Icc.mono_set Ioo_subset_Icc_self
    · exact (ae_restrict_iff' measurableSet_Ioo).mpr (Filter.Eventually.of_forall fun t ht => by
        have : 0 < t := ht.1
        simp only [Pi.zero_apply]; linarith)

theorem lintegral_Ioi_indicator_half (b : ℝ≥0∞) :
    ∫⁻ t in Ioi (0 : ℝ), {t : ℝ | ENNReal.ofReal (t / 2) < b}.indicator 1 t = 2 * b := by
  have hmeas : MeasurableSet {t : ℝ | ENNReal.ofReal (t / 2) < b} :=
    measurableSet_lt (ENNReal.measurable_ofReal.comp (measurable_id.div_const 2)) measurable_const
  rw [lintegral_indicator hmeas, Measure.restrict_restrict hmeas]
  simp only [Pi.one_apply, lintegral_const, Measure.restrict_apply MeasurableSet.univ,
    univ_inter, one_mul]
  rcases eq_or_ne b ⊤ with rfl | hb
  · have : {t : ℝ | ENNReal.ofReal (t / 2) < ⊤} ∩ Ioi 0 = Ioi 0 := by ext t; simp
    rw [this, Real.volume_Ioi, ENNReal.mul_top two_ne_zero]
  · have hset : {t : ℝ | ENNReal.ofReal (t / 2) < b} ∩ Ioi 0 = Ioo 0 (2 * b.toReal) := by
      ext t
      simp only [mem_inter_iff, mem_ofPred_eq, mem_Ioi, mem_Ioo]
      constructor
      · rintro ⟨h1, h2⟩
        refine ⟨h2, ?_⟩
        have := (ENNReal.ofReal_lt_iff_lt_toReal (by linarith) hb).mp h1
        linarith
      · rintro ⟨h1, h2⟩
        exact ⟨(ENNReal.ofReal_lt_iff_lt_toReal (by linarith) hb).mpr (by linarith), h1⟩
    rw [hset, Real.volume_Ioo, sub_zero, ENNReal.ofReal_mul (by norm_num), ENNReal.ofReal_toReal hb]
    simp

namespace HomGauge

variable {E : Type*} [AddCommGroup E] [TopologicalSpace E] [IsTopologicalAddGroup E]
  [MeasurableSpace E] [BorelSpace E] [SecondCountableTopology E]
  {μ : Measure E} [μ.IsAddLeftInvariant] [SFinite μ] (G : HomGauge E μ)

omit [SecondCountableTopology E] [SFinite μ] in
theorem maximal_le_add (g : E → ℝ≥0∞) (s : ℝ≥0∞) (x : E) :
    G.maximal 0 g x ≤ G.maximal 0 ({y | s < g y}.indicator g) x + s := by
  refine iSup₂_le fun q _ => iSup_le fun hq => ?_
  have hq' : (0 : ℝ) < q := by exact_mod_cast hq
  have hpos := G.measure_ball_pos (0 : E) hq'
  have hfin := G.measure_ball_lt_top (0 : E) hq'
  have hpt : ∀ y, g y ≤ {y | s < g y}.indicator g y + s := by
    intro y
    by_cases h : s < g y
    · rw [indicator_of_mem (show y ∈ {y | s < g y} from h)]; exact le_self_add
    · rw [indicator_of_notMem (show y ∉ {y | s < g y} from h), zero_add]; exact not_lt.mp h
  calc (μ (G.ball 0 q))⁻¹ * ∫⁻ y in G.ball x q, g y ∂μ
      ≤ (μ (G.ball 0 q))⁻¹ * ∫⁻ y in G.ball x q, ({y | s < g y}.indicator g y + s) ∂μ := by
        gcongr with y; exact hpt y
    _ = (μ (G.ball 0 q))⁻¹ * ∫⁻ y in G.ball x q, {y | s < g y}.indicator g y ∂μ +
          (μ (G.ball 0 q))⁻¹ * (s * μ (G.ball x q)) := by
        rw [lintegral_add_right _ measurable_const, setLIntegral_const, mul_add]
    _ ≤ G.maximal 0 ({y | s < g y}.indicator g) x + s := by
        gcongr
        · rw [← G.measure_ball_zero x]
          exact G.le_maximal 0 _ x (by exact_mod_cast hq.le) hq
        · rw [G.measure_ball_zero x, mul_comm s, ← mul_assoc, ENNReal.inv_mul_cancel hpos.ne'
            hfin.ne, one_mul]

/-- **Strong type `(2,2)` of the maximal function**: `∫ (M_0 g)² ≤ 8·3^D ∫ g²`. -/
theorem lintegral_maximal_sq_le (g : E → ℝ≥0∞) (hg : Measurable g) :
    ∫⁻ x, G.maximal 0 g x ^ 2 ∂μ ≤ ENNReal.ofReal (8 * 3 ^ G.D) * ∫⁻ x, g x ^ 2 ∂μ := by
  have hM := G.measurable_maximal 0 hg
  set c : ℝ≥0∞ := ENNReal.ofReal (3 ^ G.D)
  -- layer cake in `x`
  have h1 : ∫⁻ x, G.maximal 0 g x ^ 2 ∂μ = ∫⁻ t in Ioi (0 : ℝ),
      ENNReal.ofReal (2 * t) * μ {x | ENNReal.ofReal t < G.maximal 0 g x} := by
    have hF : Measurable (fun p : E × ℝ => if ENNReal.ofReal p.2 < G.maximal 0 g p.1 then
        ENNReal.ofReal (2 * p.2) else 0) :=
      Measurable.ite (measurableSet_lt (ENNReal.measurable_ofReal.comp measurable_snd)
        (hM.comp measurable_fst)) (ENNReal.measurable_ofReal.comp
          (measurable_const.mul measurable_snd)) measurable_const
    have e1 : ∀ x, G.maximal 0 g x ^ 2 = ∫⁻ t in Ioi (0 : ℝ),
        (if ENNReal.ofReal t < G.maximal 0 g x then ENNReal.ofReal (2 * t) else 0) := by
      intro x
      rw [← lintegral_Ioi_indicator_two_mul]
      refine lintegral_congr fun t => ?_
      by_cases h : ENNReal.ofReal t < G.maximal 0 g x <;> simp [indicator, h]
    simp_rw [e1]
    rw [lintegral_lintegral_swap hF.aemeasurable]
    refine lintegral_congr fun t => ?_
    have hS : MeasurableSet {x | ENNReal.ofReal t < G.maximal 0 g x} :=
      measurableSet_lt measurable_const hM
    rw [← lintegral_indicator_const hS]
    refine lintegral_congr fun x => ?_
    by_cases h : ENNReal.ofReal t < G.maximal 0 g x <;> simp [indicator, h]
  -- the level set estimate
  have h2 : ∀ t : ℝ, 0 < t → ENNReal.ofReal (2 * t) * μ {x | ENNReal.ofReal t < G.maximal 0 g x} ≤
      4 * c * ∫⁻ x, {y | ENNReal.ofReal (t / 2) < g y}.indicator g x ∂μ := by
    intro t ht
    set s := ENNReal.ofReal (t / 2)
    have hs0 : s ≠ 0 := by simpa [s] using ht
    have hsub : {x | ENNReal.ofReal t < G.maximal 0 g x} ⊆
        {x | s < G.maximal 0 ({y | s < g y}.indicator g) x} := by
      intro x hx
      simp only [mem_ofPred_eq] at hx ⊢
      by_contra hle
      push Not at hle
      have := (G.maximal_le_add g s x).trans (add_le_add hle le_rfl)
      rw [← ENNReal.ofReal_add (by linarith) (by linarith), add_halves] at this
      exact absurd hx (not_lt.mpr this)
    have hw := G.measure_maximal_gt_le ({y | s < g y}.indicator g) hs0
    calc ENNReal.ofReal (2 * t) * μ {x | ENNReal.ofReal t < G.maximal 0 g x}
        ≤ ENNReal.ofReal (2 * t) * (c / s * ∫⁻ x, {y | s < g y}.indicator g x ∂μ) := by
          gcongr; exact (measure_mono hsub).trans hw
      _ = (ENNReal.ofReal (2 * t) / s) * c * ∫⁻ x, {y | s < g y}.indicator g x ∂μ := by
          rw [ENNReal.div_eq_inv_mul, ENNReal.div_eq_inv_mul]; ring
      _ = 4 * c * ∫⁻ x, {y | s < g y}.indicator g x ∂μ := by
          congr 2
          rw [← ENNReal.ofReal_div_of_pos (by linarith)]
          rw [show 2 * t / (t / 2) = 4 by field_simp; ring]
          simp
  -- layer cake in `t`
  have hG : Measurable (fun p : ℝ × E => if ENNReal.ofReal (p.1 / 2) < g p.2 then g p.2 else 0) :=
    Measurable.ite (measurableSet_lt (ENNReal.measurable_ofReal.comp
      (measurable_fst.div_const 2)) (hg.comp measurable_snd)) (hg.comp measurable_snd)
      measurable_const
  calc ∫⁻ x, G.maximal 0 g x ^ 2 ∂μ
      ≤ ∫⁻ t in Ioi (0 : ℝ), 4 * c * ∫⁻ x, {y | ENNReal.ofReal (t / 2) < g y}.indicator g x ∂μ := by
        rw [h1]
        exact setLIntegral_mono' measurableSet_Ioi fun t ht => h2 t ht
    _ = 4 * c * ∫⁻ x, g x * (∫⁻ t in Ioi (0 : ℝ),
          {t : ℝ | ENNReal.ofReal (t / 2) < g x}.indicator 1 t) ∂μ := by
        rw [lintegral_const_mul' _ _ (ENNReal.mul_ne_top (by simp) ENNReal.ofReal_ne_top)]
        congr 1
        have e2 : ∀ t : ℝ, ∫⁻ x, {y | ENNReal.ofReal (t / 2) < g y}.indicator g x ∂μ =
            ∫⁻ x, (if ENNReal.ofReal (t / 2) < g x then g x else 0) ∂μ := fun t =>
          lintegral_congr fun x => by
            by_cases h : ENNReal.ofReal (t / 2) < g x <;> simp [indicator, h]
        simp_rw [e2]
        rw [lintegral_lintegral_swap hG.aemeasurable]
        refine lintegral_congr fun x => ?_
        have hmI : Measurable (fun t : ℝ => {t : ℝ | ENNReal.ofReal (t / 2) < g x}.indicator
            (1 : ℝ → ℝ≥0∞) t) := measurable_one.indicator (measurableSet_lt
              (ENNReal.measurable_ofReal.comp (measurable_id.div_const 2)) measurable_const)
        rw [← lintegral_const_mul (g x) hmI]
        refine lintegral_congr fun t => ?_
        simp only [indicator, mem_ofPred_eq, Pi.one_apply]
        split_ifs <;> simp
    _ = 8 * c * ∫⁻ x, g x ^ 2 ∂μ := by
        simp_rw [lintegral_Ioi_indicator_half]
        rw [show (fun x => g x * (2 * g x)) = fun x => 2 * g x ^ 2 by ext x; ring,
          lintegral_const_mul' _ _ (by simp)]
        ring
    _ = _ := by
        rw [ENNReal.ofReal_mul (by norm_num), ENNReal.ofReal_ofNat]

omit [IsTopologicalAddGroup E] [BorelSpace E] [SecondCountableTopology E]
  [μ.IsAddLeftInvariant] [SFinite μ] in
theorem measure_lt_eq (r : ℝ) (hr : 0 < r) :
    μ {y | G.ρ y < r} = ENNReal.ofReal (r ^ G.D) * μ {y | G.ρ y ≤ 1} := by
  -- continuity from below along `r - 1/(k+1)`
  have hU : {y | G.ρ y < r} = ⋃ k : ℕ, {y | G.ρ y ≤ r - r / (k + 2)} := by
    ext y
    simp only [mem_ofPred_eq, mem_iUnion]
    constructor
    · intro h
      obtain ⟨k, hk⟩ := exists_nat_gt (r / (r - G.ρ y))
      refine ⟨k, ?_⟩
      have hpos : 0 < r - G.ρ y := by linarith
      rw [div_lt_iff₀ hpos] at hk
      have : r / (k + 2) ≤ r - G.ρ y := by
        rw [div_le_iff₀ (by positivity)]; nlinarith
      linarith
    · rintro ⟨k, hk⟩
      have : 0 < r / (k + 2) := by positivity
      linarith
  have hmono : Monotone fun k : ℕ => {y | G.ρ y ≤ r - r / (k + 2)} := by
    intro a b hab y hy
    simp only [mem_ofPred_eq] at hy ⊢
    have : r / (b + 2) ≤ r / (a + 2) :=
      div_le_div_of_nonneg_left hr.le (by positivity) (by exact_mod_cast (by omega : a + 2 ≤ b + 2))
    linarith
  rw [hU, hmono.measure_iUnion]
  have hval : ∀ k : ℕ, μ {y | G.ρ y ≤ r - r / (k + 2)} =
      ENNReal.ofReal ((r - r / (k + 2)) ^ G.D) * μ {y | G.ρ y ≤ 1} := by
    intro k
    refine G.vol _ ?_
    have : r / (k + 2) < r := div_lt_self hr (by linarith [(Nat.cast_nonneg k : (0 : ℝ) ≤ k)])
    linarith
  simp_rw [hval]
  rw [← ENNReal.iSup_mul]
  congr 1
  refine le_antisymm (iSup_le fun k => ENNReal.ofReal_le_ofReal
    (Real.rpow_le_rpow (by
      have : r / (k + 2) < r := div_lt_self hr (by linarith [(Nat.cast_nonneg k : (0 : ℝ) ≤ k)])
      linarith) (by have : 0 < r / (k + 2) := by positivity
                    linarith) G.D_pos.le)) ?_
  -- the supremum reaches `r^D`
  have hlim : Filter.Tendsto (fun k : ℕ => ENNReal.ofReal ((r - r / (k + 2)) ^ G.D))
      Filter.atTop (nhds (ENNReal.ofReal (r ^ G.D))) := by
    refine ENNReal.tendsto_ofReal ?_
    have h1 : Filter.Tendsto (fun k : ℕ => r - r / ((k : ℝ) + 2)) Filter.atTop (nhds (r - 0)) := by
      refine tendsto_const_nhds.sub ?_
      refine Filter.Tendsto.div_atTop tendsto_const_nhds ?_
      exact Filter.tendsto_atTop_add_const_right _ 2 tendsto_natCast_atTop_atTop
    rw [sub_zero] at h1
    exact (Real.continuousAt_rpow_const r G.D (Or.inl hr.ne')).tendsto.comp h1
  exact le_of_tendsto' hlim fun k => le_iSup (fun k : ℕ => ENNReal.ofReal
    ((r - r / (k + 2)) ^ G.D)) k

omit [SecondCountableTopology E] [SFinite μ] in
theorem measure_lt_eq_ball (r : ℝ) (hr : 0 < r) : μ {y | G.ρ y < r} = μ (G.ball 0 r) := by
  rw [G.measure_lt_eq r hr, G.measure_ball_eq 0 hr]

omit [SecondCountableTopology E] [SFinite μ] in
/-- The integral over a gauge ball of real radius `R ≥ λ` is controlled by `M_λ`. -/
theorem setLIntegral_ball_le (lam : ℝ) (g : E → ℝ≥0∞) (x : E) {R : ℝ} (hR : 0 < R)
    (hlR : lam ≤ R) :
    ∫⁻ y in G.ball x R, g y ∂μ ≤ μ (G.ball 0 R) * G.maximal lam g x := by
  -- approximate `R` from above by rationals
  have hq : ∀ k : ℕ, ∃ q : ℚ, R < q ∧ (q : ℝ) < R + 1 / (k + 1) := fun k =>
    exists_rat_btwn (by have : (0 : ℝ) < 1 / (k + 1) := by positivity
                        linarith)
  choose q hq1 hq2 using hq
  have hbound : ∀ k, ∫⁻ y in G.ball x R, g y ∂μ ≤ μ (G.ball 0 (q k)) * G.maximal lam g x := by
    intro k
    have hqpos : (0 : ℝ) < q k := hR.trans (hq1 k)
    have hle := G.le_maximal lam g x (hlR.trans (hq1 k).le) (by exact_mod_cast hqpos)
    have hpos := G.measure_ball_pos x hqpos
    have hfin := G.measure_ball_lt_top x hqpos
    calc ∫⁻ y in G.ball x R, g y ∂μ ≤ ∫⁻ y in G.ball x (q k), g y ∂μ :=
          lintegral_mono_set (G.ball_mono x (hq1 k).le)
      _ = μ (G.ball x (q k)) * ((μ (G.ball x (q k)))⁻¹ * ∫⁻ y in G.ball x (q k), g y ∂μ) := by
          rw [← mul_assoc, ENNReal.mul_inv_cancel hpos.ne' hfin.ne, one_mul]
      _ ≤ μ (G.ball 0 (q k)) * G.maximal lam g x := by
          rw [G.measure_ball_zero x] at hle ⊢
          exact mul_le_mul_right hle _
  have hlim : Filter.Tendsto (fun k => μ (G.ball 0 (q k)) * G.maximal lam g x) Filter.atTop
      (nhds (μ (G.ball 0 R) * G.maximal lam g x)) := by
    by_cases hM : G.maximal lam g x = ⊤
    · have : ∀ k, μ (G.ball 0 (q k)) * G.maximal lam g x = ⊤ := fun k => by
        rw [hM, ENNReal.mul_top (G.measure_ball_pos 0 (hR.trans (hq1 k))).ne']
      simp_rw [this]
      rw [hM, ENNReal.mul_top (G.measure_ball_pos 0 hR).ne']
      exact tendsto_const_nhds
    refine ENNReal.Tendsto.mul_const ?_ (Or.inr hM)
    have hqlim : Filter.Tendsto (fun k => (q k : ℝ)) Filter.atTop (nhds R) := by
      refine tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds ?_ (fun k => (hq1 k).le)
        (fun k => (hq2 k).le)
      have := tendsto_one_div_add_atTop_nhds_zero_nat (𝕜 := ℝ)
      simpa using (tendsto_const_nhds (x := R)).add this
    have e : ∀ k, μ (G.ball 0 (q k)) = ENNReal.ofReal ((q k : ℝ) ^ G.D) * μ {y | G.ρ y ≤ 1} :=
      fun k => G.measure_ball_eq 0 (hR.trans (hq1 k))
    simp_rw [e]
    rw [G.measure_ball_eq 0 hR]
    refine ENNReal.Tendsto.mul_const ?_ (Or.inr G.vol_lt_top.ne)
    exact ENNReal.tendsto_ofReal ((Real.continuousAt_rpow_const R G.D (Or.inl hR.ne')).tendsto.comp
      hqlim)
  exact ge_of_tendsto' hlim hbound

end HomGauge

theorem lintegral_Ioi_indicator_lt (a : ℝ≥0∞) :
    ∫⁻ s in Ioi (0 : ℝ), {s : ℝ | ENNReal.ofReal s < a}.indicator 1 s = a := by
  have hmeas : MeasurableSet {s : ℝ | ENNReal.ofReal s < a} :=
    measurableSet_lt ENNReal.measurable_ofReal measurable_const
  rw [lintegral_indicator hmeas, Measure.restrict_restrict hmeas]
  simp only [Pi.one_apply, lintegral_const, Measure.restrict_apply MeasurableSet.univ,
    univ_inter, one_mul]
  rcases eq_or_ne a ⊤ with rfl | ha
  · have : {s : ℝ | ENNReal.ofReal s < ⊤} ∩ Ioi 0 = Ioi 0 := by ext s; simp
    rw [this, Real.volume_Ioi]
  · have hset : {s : ℝ | ENNReal.ofReal s < a} ∩ Ioi 0 = Ioo 0 a.toReal := by
      ext s
      simp only [mem_inter_iff, mem_ofPred_eq, mem_Ioi, mem_Ioo]
      constructor
      · rintro ⟨h1, h2⟩
        exact ⟨h2, (ENNReal.ofReal_lt_iff_lt_toReal h2.le ha).mp h1⟩
      · rintro ⟨h1, h2⟩
        exact ⟨(ENNReal.ofReal_lt_iff_lt_toReal h1.le ha).mpr h2, h1⟩
    rw [hset, Real.volume_Ioo, sub_zero, ENNReal.ofReal_toReal ha]

namespace HomGauge

variable {E : Type*} [AddCommGroup E] [TopologicalSpace E] [IsTopologicalAddGroup E]
  [MeasurableSpace E] [BorelSpace E] [SecondCountableTopology E]
  {μ : Measure E} [μ.IsAddLeftInvariant] [SFinite μ] (G : HomGauge E μ)

/-- **Majorization of approximate identities by the maximal function** (paper, Lemma 7.2): if
`W` is antitone and constant on `[0, λ]`, then `∫ g(x - y) W(ρ(y)) dy ≤ (∫ W ∘ ρ) M_λ g(x)`. -/
theorem lintegral_mul_gauge_le [μ.IsNegInvariant] {lam : ℝ} (hlam : 0 < lam) (W : ℝ → ℝ≥0∞)
    (hW : Antitone W) (hWc : ∀ t ∈ Icc 0 lam, W t = W 0) {g : E → ℝ≥0∞} (hg : Measurable g)
    (x : E) :
    ∫⁻ y, g (x - y) * W (G.ρ y) ∂μ ≤ (∫⁻ y, W (G.ρ y) ∂μ) * G.maximal lam g x := by
  set M := G.maximal lam g x
  have hV : Measurable fun y => W (G.ρ y) := hW.measurable.comp G.continuous.measurable
  have hgx : Measurable fun y => g (x - y) := hg.comp (measurable_const.sub measurable_id)
  -- the degenerate case `M = 0`
  by_cases hM0 : M = 0
  · have hball0 : ∀ q : ℚ, lam ≤ q → ∫⁻ y in G.ball x q, g y ∂μ = 0 := by
      intro q hq
      have hqpos : (0 : ℝ) < q := hlam.trans_le hq
      have h := G.le_maximal lam g x hq (by exact_mod_cast hqpos)
      rw [show G.maximal lam g x = 0 from hM0, nonpos_iff_eq_zero, mul_eq_zero] at h
      rcases h with h | h
      · exact absurd h (ENNReal.inv_ne_zero.mpr (G.measure_ball_lt_top x hqpos).ne)
      · exact h
    have hcover : (univ : Set E) ⊆ ⋃ q : {q : ℚ // lam ≤ q}, G.ball x q := by
      intro y _
      obtain ⟨q, hq⟩ := exists_rat_gt (max lam (G.ρ (x - y)))
      exact mem_iUnion.mpr ⟨⟨q, (le_max_left _ _).trans hq.le⟩, (le_max_right _ _).trans hq.le⟩
    have hg0 : ∫⁻ y, g y ∂μ = 0 := by
      rw [← setLIntegral_univ]
      refine le_antisymm ((lintegral_mono_set hcover).trans ((lintegral_iUnion_le _ _).trans ?_))
        bot_le
      exact le_of_eq (ENNReal.tsum_eq_zero.mpr fun q => hball0 q q.2)
    have hae : g =ᵐ[μ] 0 := (lintegral_eq_zero_iff hg).mp hg0
    have := lintegral_sub_left_eq_self (μ := μ) (fun z => g z * W (G.ρ (x - z))) x
    simp only [sub_sub_cancel] at this
    have hL : ∫⁻ y, g (x - y) * W (G.ρ y) ∂μ = 0 := by
      rw [this]
      refine (lintegral_congr_ae ?_).trans lintegral_zero
      filter_upwards [hae] with z hz
      simp [hz]
    rw [hL]
    exact bot_le
  -- layer cake
  have hlayer : ∀ a : ℝ≥0∞, a = ∫⁻ s in Ioi (0 : ℝ), {s : ℝ | ENNReal.ofReal s < a}.indicator 1 s :=
    fun a => (lintegral_Ioi_indicator_lt a).symm
  have hF : Measurable (fun p : E × ℝ => g (x - p.1) *
      {s : ℝ | ENNReal.ofReal s < W (G.ρ p.1)}.indicator 1 p.2) := by
    refine (hgx.comp measurable_fst).mul ?_
    have : (fun p : E × ℝ => {s : ℝ | ENNReal.ofReal s < W (G.ρ p.1)}.indicator (1 : ℝ → ℝ≥0∞) p.2)
        = fun p => if ENNReal.ofReal p.2 < W (G.ρ p.1) then 1 else 0 := by
      ext p; by_cases h : ENNReal.ofReal p.2 < W (G.ρ p.1) <;> simp [indicator, h]
    rw [this]
    exact Measurable.ite (measurableSet_lt (ENNReal.measurable_ofReal.comp measurable_snd)
      (hV.comp measurable_fst)) measurable_const measurable_const
  have hLHS : ∫⁻ y, g (x - y) * W (G.ρ y) ∂μ = ∫⁻ s in Ioi (0 : ℝ),
      ∫⁻ y, g (x - y) * {s : ℝ | ENNReal.ofReal s < W (G.ρ y)}.indicator 1 s ∂μ := by
    have e : ∀ y, g (x - y) * W (G.ρ y) = ∫⁻ s in Ioi (0 : ℝ),
        g (x - y) * {s : ℝ | ENNReal.ofReal s < W (G.ρ y)}.indicator 1 s := by
      intro y
      rw [lintegral_const_mul _ (measurable_one.indicator (measurableSet_lt
        ENNReal.measurable_ofReal measurable_const)), ← hlayer]
    simp_rw [e]
    exact lintegral_lintegral_swap hF.aemeasurable
  have hRHS : ∫⁻ y, W (G.ρ y) ∂μ = ∫⁻ s in Ioi (0 : ℝ), μ {y | ENNReal.ofReal s < W (G.ρ y)} := by
    have hF' : Measurable (fun p : E × ℝ =>
        {s : ℝ | ENNReal.ofReal s < W (G.ρ p.1)}.indicator (1 : ℝ → ℝ≥0∞) p.2) := by
      have : (fun p : E × ℝ => {s : ℝ | ENNReal.ofReal s < W (G.ρ p.1)}.indicator
          (1 : ℝ → ℝ≥0∞) p.2) = fun p => if ENNReal.ofReal p.2 < W (G.ρ p.1) then 1 else 0 := by
        ext p; by_cases h : ENNReal.ofReal p.2 < W (G.ρ p.1) <;> simp [indicator, h]
      rw [this]
      exact Measurable.ite (measurableSet_lt (ENNReal.measurable_ofReal.comp measurable_snd)
        (hV.comp measurable_fst)) measurable_const measurable_const
    conv_lhs => arg 2; ext y; rw [hlayer (W (G.ρ y))]
    rw [lintegral_lintegral_swap hF'.aemeasurable]
    refine lintegral_congr fun s => ?_
    rw [← lintegral_indicator_one (measurableSet_lt measurable_const hV)]
    refine lintegral_congr fun y => ?_
    by_cases h : ENNReal.ofReal s < W (G.ρ y) <;> simp [indicator, h]
  -- the level sets
  have hlevel : ∀ s : ℝ, 0 < s → ∫⁻ y, g (x - y) *
      {s : ℝ | ENNReal.ofReal s < W (G.ρ y)}.indicator 1 s ∂μ ≤
      μ {y | ENNReal.ofReal s < W (G.ρ y)} * M := by
    intro s hs
    set S := {y | ENNReal.ofReal s < W (G.ρ y)}
    have hSm : MeasurableSet S := measurableSet_lt measurable_const hV
    have hLS : ∫⁻ y, g (x - y) * {s : ℝ | ENNReal.ofReal s < W (G.ρ y)}.indicator 1 s ∂μ =
        ∫⁻ y in S, g (x - y) ∂μ := by
      rw [← lintegral_indicator hSm]
      refine lintegral_congr fun y => ?_
      by_cases h : ENNReal.ofReal s < W (G.ρ y) <;> simp [indicator, h, S]
    rw [hLS]
    by_cases hs0 : ENNReal.ofReal s < W 0
    · -- `S` contains the ball of radius `λ`
      have hball : {y | G.ρ y ≤ lam} ⊆ S := fun y hy => by
        simp only [S, mem_ofPred_eq]
        rw [hWc (G.ρ y) ⟨G.nonneg y, hy⟩]; exact hs0
      have h0S : (0 : E) ∈ S := hball (by simp [G.zero, hlam.le])
      by_cases hbdd : BddAbove (G.ρ '' S)
      · set R₀ := sSup (G.ρ '' S)
        set R := max R₀ lam
        have hlR : lam ≤ R := le_max_right _ _
        have hRpos : 0 < R := hlam.trans_le hlR
        have hSR : S ⊆ {y | G.ρ y ≤ R} := fun y hy =>
          (le_csSup hbdd (mem_image_of_mem _ hy)).trans (le_max_left _ _)
        have hRS : {y | G.ρ y < R} ⊆ S := by
          intro y hy
          simp only [mem_ofPred_eq] at hy
          rcases le_total lam R₀ with hl | hl
          · have hy' : G.ρ y < R₀ := by
              rwa [show R = max R₀ lam from rfl, max_eq_left hl] at hy
            obtain ⟨_, ⟨y', hy'', rfl⟩, hlt⟩ := exists_lt_of_lt_csSup
              ⟨G.ρ 0, mem_image_of_mem _ h0S⟩ hy'
            simp only [S, mem_ofPred_eq] at hy'' ⊢
            exact hy''.trans_le (hW hlt.le)
          · rw [show R = max R₀ lam from rfl, max_eq_right hl] at hy
            exact hball hy.le
        calc ∫⁻ y in S, g (x - y) ∂μ ≤ ∫⁻ y in {y | G.ρ y ≤ R}, g (x - y) ∂μ :=
              lintegral_mono_set hSR
          _ = ∫⁻ z in G.ball x R, g z ∂μ := by
              rw [← lintegral_indicator (measurableSet_le G.continuous.measurable measurable_const),
                ← lintegral_indicator (G.measurableSet_ball x R)]
              have := lintegral_sub_left_eq_self (μ := μ)
                (fun z => (G.ball x R).indicator g z) x
              rw [← this]
              refine lintegral_congr fun y => ?_
              simp only [indicator, ball, mem_ofPred_eq, sub_sub_cancel]
          _ ≤ μ (G.ball 0 R) * M := G.setLIntegral_ball_le lam g x hRpos hlR
          _ = μ {y | G.ρ y < R} * M := by rw [G.measure_lt_eq_ball R hRpos]
          _ ≤ μ S * M := by gcongr
      · -- unbounded level set: infinite measure
        have hinf : μ S = ⊤ := by
          have hge : ∀ r : ℝ, 0 < r → ENNReal.ofReal (r ^ G.D) * μ {y | G.ρ y ≤ 1} ≤ μ S := by
            intro r hr
            rw [← G.measure_lt_eq r hr]
            refine measure_mono fun z hz => ?_
            simp only [mem_ofPred_eq] at hz
            obtain ⟨_, ⟨y, hy, rfl⟩, hlt⟩ := not_bddAbove_iff.mp hbdd r
            simp only [S, mem_ofPred_eq] at hy ⊢
            exact hy.trans_le (hW (hz.trans hlt).le)
          have hlim : Filter.Tendsto (fun r : ℝ => ENNReal.ofReal (r ^ G.D) * μ {y | G.ρ y ≤ 1})
              Filter.atTop (nhds ⊤) := by
            rw [← ENNReal.top_mul G.vol_pos.ne']
            exact ENNReal.Tendsto.mul_const (ENNReal.tendsto_ofReal_atTop.comp
              (tendsto_rpow_atTop G.D_pos)) (Or.inl ENNReal.top_ne_zero)
          exact top_le_iff.mp (le_of_tendsto hlim (Filter.eventually_atTop.mpr ⟨1, fun r hr =>
            hge r (by linarith)⟩))
        rw [hinf, ENNReal.top_mul hM0]
        exact le_top
    · -- `S` is empty
      have hS : S = ∅ := by
        ext y
        simp only [S, mem_ofPred_eq, mem_empty_iff_false, iff_false, not_lt]
        exact (hW (G.nonneg y)).trans (not_lt.mp hs0)
      rw [hS, Measure.restrict_empty, lintegral_zero_measure]
      exact bot_le
  have hanti : Antitone fun s : ℝ => μ {y | ENNReal.ofReal s < W (G.ρ y)} := by
    intro a b hab
    refine measure_mono fun y hy => ?_
    simp only [mem_ofPred_eq] at hy ⊢
    exact (ENNReal.ofReal_le_ofReal hab).trans_lt hy
  rw [hLHS, hRHS, ← lintegral_mul_const _ hanti.measurable]
  exact setLIntegral_mono' measurableSet_Ioi fun s hs => hlevel s hs

omit [SecondCountableTopology E] [SFinite μ] in
/-- Comparison of maximal functions at nearby points: if `ρ(x − y) ≤ λ`, then
`M_λ g(x) ≤ 2^D M_0 g(y)`. -/
theorem maximal_le_of_rho_sub_le (g : E → ℝ≥0∞) {x y : E} {lam : ℝ}
    (hxy : G.ρ (x - y) ≤ lam) :
    G.maximal lam g x ≤ ENNReal.ofReal (2 ^ G.D) * G.maximal 0 g y := by
  refine iSup₂_le fun q hq => iSup_le fun hq0 => ?_
  have hq' : (0 : ℝ) < q := by exact_mod_cast hq0
  have hsub : G.ball x q ⊆ G.ball y (2 * q) := by
    intro w hw
    simp only [ball, Set.mem_ofPred_eq] at hw ⊢
    have := G.add_le (y - x) (x - w)
    rw [sub_add_sub_cancel] at this
    have h2 : G.ρ (y - x) = G.ρ (x - y) := by rw [← G.neg (x - y), neg_sub]
    linarith
  have hpos := G.measure_ball_pos (0 : E) hq'
  have hfin := G.measure_ball_lt_top (0 : E) hq'
  have hmul := G.measure_ball_mul (0 : E) (c := 2) (by norm_num) hq'
  have h2q : ((2 * q : ℚ) : ℝ) = 2 * (q : ℝ) := by push_cast; ring
  have hle := G.le_maximal 0 g y (q := 2 * q) (by positivity) (by positivity)
  rw [h2q, G.measure_ball_zero y] at hle
  calc (μ (G.ball 0 q))⁻¹ * ∫⁻ w in G.ball x q, g w ∂μ
      ≤ (μ (G.ball 0 q))⁻¹ * ∫⁻ w in G.ball y (2 * q), g w ∂μ := by
        gcongr
    _ = ENNReal.ofReal (2 ^ G.D) * ((μ (G.ball 0 (2 * q)))⁻¹ *
          ∫⁻ w in G.ball y (2 * q), g w ∂μ) := by
        rw [hmul, ENNReal.mul_inv (Or.inr hfin.ne) (Or.inr hpos.ne'), ← mul_assoc, ← mul_assoc,
          ENNReal.mul_inv_cancel (by simp [Real.rpow_pos_of_pos (by norm_num : (0:ℝ) < 2)])
            ENNReal.ofReal_ne_top, one_mul]
    _ ≤ _ := by gcongr

end HomGauge

end Auto
