/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/
import Mathlib

/-!
# Smoothness of parametric integrals (the higher-order Leibniz integral rule)

**Theorem (Leibniz integral rule, `C^k` version).** Let `E` be a finite-dimensional real normed
space and `F` a real Banach space, let `Φ : E × ℝ → F` be `C^k` (jointly), and suppose that there is a compact set `K ⊆ ℝ`
such that `Φ (x, t) = 0` whenever `t ∉ K`. Then the parametric integral
`x ↦ ∫ t, Φ (x, t) dt` is `C^k` on `E`, and its derivative is obtained by differentiating under
the integral sign.

The first-order case is Mathlib's `hasFDerivAt_integral_of_dominated_of_fderiv_le`; the general
case follows by induction on `k`, since the partial derivative `∂ₓΦ` is `C^{k-1}` and vanishes for
`t ∉ K` as well.

## References

* Leibniz integral rule (differentiation under the integral sign):
  <https://en.wikipedia.org/wiki/Leibniz_integral_rule>.
* Mathlib: `hasFDerivAt_integral_of_dominated_of_fderiv_le` in
  `Mathlib/Analysis/Calculus/ParametricIntegral.lean` (first-order version).
-/

noncomputable section

open MeasureTheory Set Metric

namespace Auto

universe u

variable {E : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

/-- The partial derivative in the parameter variable: `∂ₓΦ(x, t) = DΦ(x, t) ∘ (v ↦ (v, 0))`. -/
def partialFst {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F] (Φ : E × ℝ → F)
    (p : E × ℝ) : E →L[ℝ] F :=
  (fderiv ℝ Φ p).comp (ContinuousLinearMap.inl ℝ E ℝ)

omit [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E] in
theorem integral_eq_setIntegral_of_vanish {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F]
    {Φ : E × ℝ → F} {K : Set ℝ} (hsupp : ∀ x t, t ∉ K → Φ (x, t) = 0) (x : E) :
    ∫ t, Φ (x, t) = ∫ t in K, Φ (x, t) :=
  (setIntegral_eq_integral_of_forall_compl_eq_zero fun t ht => hsupp x t ht).symm

/-- Order `0`: the parametric integral of a continuous function vanishing off a compact set is
continuous. -/
theorem continuous_integral_of_vanish {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [CompleteSpace F] {Φ : E × ℝ → F} (hΦ : Continuous Φ) {K : Set ℝ} (hK : IsCompact K)
    (hsupp : ∀ x t, t ∉ K → Φ (x, t) = 0) : Continuous fun x => ∫ t, Φ (x, t) := by
  have : (fun x => ∫ t, Φ (x, t)) = fun x => ∫ t in K, Φ (x, t) :=
    funext (integral_eq_setIntegral_of_vanish hsupp)
  rw [this]
  exact continuous_parametric_integral_of_continuous (f := fun x t => Φ (x, t))
    (hΦ.comp continuous_id) hK

omit [FiniteDimensional ℝ E] in
theorem partialFst_vanish {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F]
    {Φ : E × ℝ → F} {K : Set ℝ} (hK : IsClosed K) (hsupp : ∀ x t, t ∉ K → Φ (x, t) = 0)
    (x : E) {t : ℝ} (ht : t ∉ K) : partialFst Φ (x, t) = 0 := by
  have hloc : Φ =ᶠ[nhds (x, t)] fun _ => 0 := by
    have hopen : IsOpen {p : E × ℝ | p.2 ∉ K} := hK.isOpen_compl.preimage continuous_snd
    filter_upwards [hopen.mem_nhds ht] with p hp
    exact hsupp p.1 p.2 hp
  unfold partialFst
  rw [hloc.fderiv_eq, fderiv_const_apply, ContinuousLinearMap.zero_comp]

omit [FiniteDimensional ℝ E] in
theorem hasFDerivAt_partialFst {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F]
    {Φ : E × ℝ → F} (hΦ : Differentiable ℝ Φ) (x : E) (t : ℝ) :
    HasFDerivAt (fun y => Φ (y, t)) (partialFst Φ (x, t)) x := by
  have h1 : HasFDerivAt (fun y : E => (y, t)) (ContinuousLinearMap.inl ℝ E ℝ) x :=
    hasFDerivAt_prodMk_left x t
  exact (hΦ (x, t)).hasFDerivAt.comp x h1

/-- The inductive step: differentiation under the integral sign. -/
theorem hasFDerivAt_integral_of_vanish {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [CompleteSpace F] {Φ : E × ℝ → F} (hΦ : ContDiff ℝ 1 Φ) {K : Set ℝ} (hK : IsCompact K)
    (hsupp : ∀ x t, t ∉ K → Φ (x, t) = 0) (x₀ : E) :
    HasFDerivAt (fun x => ∫ t, Φ (x, t)) (∫ t, partialFst Φ (x₀, t)) x₀ := by
  have hdiff : Differentiable ℝ Φ := hΦ.differentiable one_ne_zero
  have hcont' : Continuous (partialFst Φ) :=
    ((hΦ.continuous_fderiv one_ne_zero).clm_comp continuous_const)
  -- a uniform bound for the partial derivative on `closedBall x₀ 1 × K`
  have hcpt : IsCompact (closedBall x₀ 1 ×ˢ K) := (isCompact_closedBall x₀ 1).prod hK
  obtain ⟨C, hC⟩ := hcpt.exists_bound_of_continuousOn hcont'.continuousOn
  have hbound : ∀ t, ∀ x ∈ ball x₀ 1, ‖partialFst Φ (x, t)‖ ≤ K.indicator (fun _ => C) t := by
    intro t x hx
    by_cases ht : t ∈ K
    · rw [indicator_of_mem ht]
      exact hC (x, t) ⟨ball_subset_closedBall hx, ht⟩
    · rw [indicator_of_notMem ht, partialFst_vanish hK.isClosed hsupp x ht, norm_zero]
  have hint : ∀ x, Integrable fun t => Φ (x, t) := by
    intro x
    have hc : Continuous fun t => Φ (x, t) := hΦ.continuous.comp (Continuous.prodMk_right x)
    refine hc.integrable_of_hasCompactSupport (HasCompactSupport.intro hK fun t ht => hsupp x t ht)
  refine hasFDerivAt_integral_of_dominated_of_fderiv_le (ball_mem_nhds x₀ one_pos)
    (Filter.Eventually.of_forall fun x => (hint x).aestronglyMeasurable) (hint x₀)
    (hcont'.comp (Continuous.prodMk_right x₀)).aestronglyMeasurable
    (Filter.Eventually.of_forall fun t x hx => hbound t x hx)
    ((integrableOn_const hK.measure_lt_top.ne).integrable_indicator hK.measurableSet)
    (Filter.Eventually.of_forall fun t x _ => hasFDerivAt_partialFst hdiff x t)

omit [FiniteDimensional ℝ E] in
theorem contDiff_partialFst {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F]
    {Φ : E × ℝ → F} {n : ℕ} (hΦ : ContDiff ℝ (n + 1) Φ) : ContDiff ℝ n (partialFst Φ) := by
  unfold partialFst
  exact (hΦ.fderiv_right (by norm_cast)).clm_comp contDiff_const

/-- **Leibniz integral rule, finite order.** If `Φ : E × ℝ → F` is `C^n` and vanishes for `t`
outside a compact set `K`, then `x ↦ ∫ Φ(x, t) dt` is `C^n`. -/
theorem contDiff_integral_of_vanish_nat (n : ℕ) :
    ∀ {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F] [CompleteSpace F] {Φ : E × ℝ → F},
      ContDiff ℝ n Φ → ∀ {K : Set ℝ}, IsCompact K → (∀ x t, t ∉ K → Φ (x, t) = 0) →
        ContDiff ℝ n fun x => ∫ t, Φ (x, t) := by
  induction n with
  | zero =>
    intro F _ _ _ Φ hΦ K hK hsupp
    rw [Nat.cast_zero, contDiff_zero] at hΦ ⊢
    exact continuous_integral_of_vanish hΦ hK hsupp
  | succ n ih =>
    intro F _ _ _ Φ hΦ K hK hsupp
    rw [Nat.cast_succ, contDiff_succ_iff_hasFDerivAt]
    refine ⟨fun x => ∫ t, partialFst Φ (x, t), ?_, fun x =>
      hasFDerivAt_integral_of_vanish (hΦ.of_le (by exact_mod_cast Nat.le_add_left 1 n)) hK hsupp x⟩
    exact ih (contDiff_partialFst hΦ) hK fun x t ht => partialFst_vanish hK.isClosed hsupp x ht

/-- **Leibniz integral rule, `C^∞` version.** If `Φ : E × ℝ → F` is smooth and vanishes for `t`
outside a compact set `K`, then `x ↦ ∫ Φ(x, t) dt` is smooth. -/
theorem contDiff_integral_of_vanish {F : Type u} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [CompleteSpace F] {Φ : E × ℝ → F} (hΦ : ContDiff ℝ ((⊤ : ℕ∞) : WithTop ℕ∞) Φ) {K : Set ℝ} (hK : IsCompact K)
    (hsupp : ∀ x t, t ∉ K → Φ (x, t) = 0) :
    ContDiff ℝ ((⊤ : ℕ∞) : WithTop ℕ∞) fun x => ∫ t, Φ (x, t) :=
  contDiff_infty.mpr fun n =>
    contDiff_integral_of_vanish_nat n (hΦ.of_le (by exact_mod_cast le_top)) hK hsupp

end Auto
